import {randomUUID} from 'node:crypto'

import {expect, test} from '@playwright/test'
import {encode} from 'next-auth/jwt'

import {campaignIds} from '../../.github/scripts/campaign-fixtures.mjs'

const frontUrl = 'https://127.0.0.1:3443'
test.use({ignoreHTTPSErrors: true, reducedMotion: 'reduce'})

test.beforeEach(async ({page}) => {
  await page.route('**/*', route => [frontUrl, 'http://127.0.0.1:3417'].includes(new URL(route.request().url()).origin) ? route.continue() : route.abort())
  await page.clock.setFixedTime(new Date('2026-11-01T12:00:00Z'))
})

async function authenticate(context, role = 'preleveur') {
  const apiToken = `browser-test-campaign-${role}-${randomUUID()}`
  const token = await encode({secret: 'browser-tests-only-never-a-real-secret', token: {
    sub: campaignIds.user, token: apiToken, role: role.startsWith('admin') ? 'ADMIN' : role === 'instructor' ? 'INSTRUCTOR' : 'DECLARANT', permissions: [],
    declarantRole: role === 'collector' ? 'COLLECTEUR' : 'PRELEVEUR',
    apiExpiresAt: new Date(Date.now() + 3_600_000).toISOString(), infoRefreshedAt: Date.now(),
    userInfo: {id: campaignIds.user, email: 'campaign@example.test', declarantRole: role === 'collector' ? 'COLLECTEUR' : 'PRELEVEUR'}
  }, maxAge: 3600})
  await context.addCookies(['next-auth.session-token', '__Secure-next-auth.session-token'].map(name => ({name, value: token, url: frontUrl, httpOnly: true, secure: true, sameSite: 'Lax'})))
  return async () => (await context.request.get('http://127.0.0.1:3431/api/__campaign-requests', {headers: {authorization: `Bearer ${apiToken}`}})).json()
}

const responseUrl = `${frontUrl}/campagnes/${campaignIds.campaign}/reponses/${campaignIds.response}`
const seasonNeedsTitle = 'Demande étiage du 1er juin au 31 octobre 2027'
const offSeasonNeedsTitle = 'Demande hors-étiage du 1er novembre 2027 au 31 mai 2028'

test('deux compteurs : brouillon incomplet, reprise, envoi et modification sans nouvelle déclaration client', async ({page, context}, testInfo) => {
  const requests = await authenticate(context)
  await page.goto(responseUrl)
  await expect(page.getByRole('heading', {name: /Code comptage : 001/})).toBeVisible()
  await expect(page.getByRole('heading', {name: 'Compteur SYNTH-M1', exact: true})).toBeVisible()
  await expect(page.getByRole('heading', {name: 'Compteur SYNTH-M2', exact: true})).toBeVisible()
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('123')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  const saveFeedback = page.getByRole('region', {name: 'Enregistrement de la réponse', exact: true}).getByRole('status')
  await expect(saveFeedback).toHaveText('Brouillon enregistré.')
  await expect(saveFeedback).toBeInViewport()
  await page.reload()
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveValue('123')
  await expect(page.locator('[name="meters.1.offSeason.indexStart"]')).toHaveValue('')
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Vérifiez les champs signalés avant d’envoyer votre réponse.', {exact: true})).toBeVisible()
  expect((await requests()).length).toBe(1)
  for (const input of await page.locator('form input[inputmode="decimal"]').all()) await input.fill('0')
  for (const crops of await page.getByRole('button', {name: 'Cultures irriguées', exact: true}).all()) {
    await crops.click()
    await page.getByRole('option', {name: 'Aucune', exact: true}).click()
    await page.keyboard.press('Escape')
  }
  for (const usage of await page.getByRole('combobox').all()) {
    await usage.fill('Aspersion')
    await page.getByRole('option', {name: /Aspersion/}).click()
  }
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  await expect(page.getByRole('heading', {name: /volumes en attente de vérification/i})).toBeVisible()
  const writes = await requests()
  expect(writes).toHaveLength(2)
  expect(writes[1].body.revision).toBe(1)
  expect(writes[1].body.data.meters.map(meter => meter.compteurId)).toEqual([campaignIds.meter, campaignIds.secondMeter])
  expect(writes[1].body.data.meters.map(meter => [meter.offSeason.crops, meter.season.crops])).toEqual([[['Aucune'], ['Aucune']], [['Aucune'], ['Aucune']]])
  expect(writes[1].body.data.needs).toMatchObject({season: {crops: ['Aucune']}, offSeason: {crops: ['Aucune']}})
  expect(writes[1].path.endsWith('/submit')).toBe(true)
  await expect(page.getByRole('button', {name: 'Cultures irriguées', exact: true})).toHaveCount(0)
  await page.getByRole('button', {name: 'Modifier ma réponse', exact: true}).click()
  await page.locator('[name="needs.season.volume"]').fill('20')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText(/Le collecteur voit votre dernière réponse envoyée/)).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({path: testInfo.outputPath('formulaire-campagne.png'), fullPage: true})
})

test('numéro absent et conflit : la saisie est conservée, aucune valeur inventée', async ({page, context}) => {
  const requests = await authenticate(context, 'missing-conflict')
  await page.goto(responseUrl)
  await expect(page.getByLabel('Numéro du compteur', {exact: true})).toHaveValue('')
  await page.getByLabel('Numéro du compteur', {exact: true}).fill('MANUEL-001')
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('0')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText(/La réponse a été modifiée/)).toBeVisible()
  await expect(page.getByLabel('Numéro du compteur', {exact: true})).toHaveValue('MANUEL-001')
  expect((await requests())[0].body.data.meters[0].compteurId).toBeNull()
})

test('Mon activité ouvre directement la réponse unique, avec un retour clair et sans filtres', async ({page, context}, testInfo) => {
  await authenticate(context)
  await page.goto(`${frontUrl}/tableau-de-bord`)
  const invitation = page.getByRole('region', {name: 'Mes index et mes besoins', exact: true})
  await expect(invitation).toBeVisible()
  await expect(invitation).not.toContainText(/exploitation/i)
  await expect(page.getByRole('heading', {name: 'Autres déclarations', exact: true})).toBeVisible()
  await page.screenshot({path: testInfo.outputPath('mon-activite-campagne.png'), fullPage: true})
  await invitation.getByRole('link', {name: 'Compléter ma réponse', exact: true}).click()
  await expect(page).toHaveURL(responseUrl)
  await expect(page.getByRole('searchbox')).toHaveCount(0)
  await expect(page.getByText(/Vous pouvez préparer votre réponse en brouillon/)).toHaveCount(0)
  await page.getByRole('link', {name: 'Mon activité', exact: true}).last().click()
  await expect(page).toHaveURL(`${frontUrl}/tableau-de-bord`)
})

test('plusieurs comptages : une liste simple sans recherche, sans confondre deux réponses du même point', async ({page, context}) => {
  await authenticate(context, 'multiple')
  await page.goto(`${frontUrl}/campagnes/${campaignIds.campaign}`)
  await expect(page.getByText(/Code comptage : 001/)).toBeVisible()
  await expect(page.getByText(/Code comptage : 002/)).toBeVisible()
  await expect(page.getByRole('searchbox')).toHaveCount(0)
  await expect(page.getByRole('button', {name: 'Filtrer', exact: true})).toHaveCount(0)
  await expect(page.getByRole('main')).not.toContainText(/exploitation/i)
  await page.locator(`a[href="/campagnes/${campaignIds.campaign}/reponses/${campaignIds.response}"]`).click()
  await expect(page).toHaveURL(responseUrl)
})

test('une collecte clôturée ouvre la réponse en lecture seule avec une explication', async ({page, context}) => {
  const requests = await authenticate(context, 'ended')
  await page.goto(`${frontUrl}/tableau-de-bord`)
  const invitation = page.getByRole('region', {name: 'Mes index et mes besoins', exact: true})
  await expect(invitation).toContainText('Réponse non envoyée')
  await invitation.getByRole('link', {name: 'Consulter ma réponse', exact: true}).click()
  await expect(page).toHaveURL(responseUrl)
  await expect(page.getByText('Cette collecte est clôturée. Votre réponse reste consultable.', {exact: true})).toBeVisible()
  await expect(page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true})).toHaveCount(0)
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveAttribute('readonly', '')
  expect(await requests()).toHaveLength(0)
})

test('un refus de permission reste compréhensible et conserve les valeurs saisies', async ({page, context}) => {
  const requests = await authenticate(context, 'forbidden')
  await page.goto(responseUrl)
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('12')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByRole('main')).not.toContainText('INSUFFICIENT_PERMISSIONS')
  await expect(page.getByText(/Vous n’avez pas les droits/)).toBeVisible()
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveValue('12')
  expect(await requests()).toHaveLength(1)
})

test('les volumes acceptent la virgule et les milliers, les usages se sélectionnent au clavier', async ({page, context}) => {
  const requests = await authenticate(context)
  await page.goto(responseUrl)
  const volume = page.locator('[name="needs.season.volume"]')
  await volume.fill('12 345,67')
  await expect(volume).toHaveValue(/12\s345,67/)
  const usage = page.getByRole('group', {name: seasonNeedsTitle, exact: true}).getByRole('combobox')
  await usage.fill('Asper')
  await usage.press('ArrowDown')
  await usage.press('Enter')
  await expect(page.getByRole('option')).toHaveCount(0)
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  const writes = await requests()
  expect(writes[0].body.data.needs.season.volume).toBe('12345.67')
  expect(writes[0].body.data.needs.season.usageId).toBe(campaignIds.usage)
  await page.reload()
  await expect(volume).toHaveValue(/12\s345,67/)
})

test('les périodes des besoins gardent leurs dates et couleurs, les catégories et cultures se sélectionnent indépendamment', async ({page, context}) => {
  const requests = await authenticate(context)
  await page.goto(responseUrl)
  const seasonNeeds = page.getByRole('group', {name: seasonNeedsTitle, exact: true})
  const offSeasonNeeds = page.getByRole('group', {name: offSeasonNeedsTitle, exact: true})
  await expect(seasonNeeds).toHaveCSS('background-color', 'rgb(255, 249, 230)')
  await expect(seasonNeeds).toHaveCSS('border-top-color', 'rgb(195, 153, 42)')
  await expect(offSeasonNeeds).toHaveCSS('background-color', 'rgb(238, 242, 250)')
  await expect(offSeasonNeeds).toHaveCSS('border-top-color', 'rgb(70, 95, 157)')
  await expect(page.getByRole('group', {name: 'Étiage 2026', exact: true}).first()).toHaveCSS('background-color', 'rgb(255, 249, 230)')
  await expect(page.getByRole('group', {name: 'Hors étiage 2025–2026', exact: true}).first()).toHaveCSS('background-color', 'rgb(238, 242, 250)')
  expect(await seasonNeeds.evaluate(element => element.nextElementSibling?.querySelector('legend')?.textContent)).toBe(offSeasonNeedsTitle)
  const crops = seasonNeeds.getByRole('button', {name: 'Cultures irriguées', exact: true})
  await crops.click()
  const choices = page.getByRole('listbox', {name: 'Cultures irriguées', exact: true})
  await expect(choices).toHaveAttribute('aria-multiselectable', 'true')
  const parent = choices.getByRole('option', {name: 'Céréales', exact: true})
  const child = choices.getByRole('option', {name: 'Maïs grain', exact: true})
  const parentLabel = parent.locator('[data-crop-level="parent"]')
  const childLabel = child.locator('[data-crop-level="child"]')
  await expect(parentLabel).toBeVisible()
  await expect(childLabel).toBeVisible()
  expect((await childLabel.boundingBox()).x).toBeGreaterThan((await parentLabel.boundingBox()).x + 15)
  await parent.click()
  await expect(parent).toHaveAttribute('aria-selected', 'true')
  await expect(child).toHaveAttribute('aria-selected', 'false')
  await child.click()
  await choices.getByRole('option', {name: 'Oléagineux', exact: true}).click()
  await expect(parent).toHaveAttribute('aria-selected', 'true')
  await expect(child).toHaveAttribute('aria-selected', 'true')
  await expect(choices.getByRole('option', {name: 'Blé', exact: true})).toHaveAttribute('aria-selected', 'false')
  await page.keyboard.press('Escape')
  await expect(crops).toBeFocused()
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  expect((await requests())[0].body.data.needs).toMatchObject({season: {crops: ['Céréales', 'Maïs grain', 'Oléagineux']}, offSeason: {crops: []}})
  await page.reload()
  await crops.click()
  for (const name of ['Céréales', 'Maïs grain', 'Oléagineux']) await expect(choices.getByRole('option', {name, exact: true})).toHaveAttribute('aria-selected', 'true')
  await expect(choices.getByRole('option', {name: 'Blé', exact: true})).toHaveAttribute('aria-selected', 'false')
  await page.keyboard.press('Escape')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
})

test('le menu des cultures reste cliquable au-dessus de la barre d’enregistrement', async ({page, context}) => {
  const requests = await authenticate(context)
  await page.goto(responseUrl)
  const crops = page.getByRole('button', {name: 'Cultures irriguées', exact: true}).first()
  await expect(crops).toBeEnabled()
  await crops.scrollIntoViewIfNeeded()
  await crops.evaluate(element => window.scrollBy(0, element.getBoundingClientRect().bottom - (window.innerHeight - 260)))
  await crops.click()
  const popup = page.locator('.grouped-multiselect-popup')
  const toolbar = page.getByRole('region', {name: 'Enregistrement de la réponse', exact: true})
  await expect(popup).toBeVisible()
  await expect(toolbar).toBeInViewport()
  const menuBounds = await popup.boundingBox()
  const toolbarBounds = await toolbar.boundingBox()
  const left = Math.max(menuBounds.x, toolbarBounds.x)
  const right = Math.min(menuBounds.x + menuBounds.width, toolbarBounds.x + toolbarBounds.width)
  const top = Math.max(menuBounds.y, toolbarBounds.y)
  const bottom = Math.min(menuBounds.y + menuBounds.height, toolbarBounds.y + toolbarBounds.height)
  expect(right).toBeGreaterThan(left)
  expect(bottom).toBeGreaterThan(top)
  const point = {x: (left + right) / 2, y: (top + bottom) / 2}
  expect(await popup.evaluate((element, {x, y}) => element.contains(document.elementFromPoint(x, y)), point)).toBe(true)
  await page.mouse.click(point.x, point.y)
  await expect(page.getByRole('option', {selected: true})).toHaveCount(1)
  expect(await requests()).toHaveLength(0)
  await page.keyboard.press('Escape')
  await expect(crops).toBeFocused()
  await expect(popup).toHaveCount(0)
  await expect(toolbar.getByRole('button', {name: 'Enregistrer le brouillon', exact: true})).toBeVisible()
})

test('la recherche des cultures fonctionne au clavier et Aucune exclut les autres choix', async ({page, context}) => {
  const requests = await authenticate(context)
  await page.goto(responseUrl)
  const crops = page.getByRole('button', {name: 'Cultures irriguées', exact: true}).first()
  await expect(crops).toBeEnabled()
  await crops.focus()
  await crops.press('Enter')
  const search = page.getByRole('textbox', {name: 'Rechercher dans cultures irriguées', exact: true})
  await expect(search).toBeFocused()
  await search.fill('mais grain')
  await expect(page.getByRole('option')).toHaveCount(1)
  await search.press('Enter')
  expect(await requests()).toHaveLength(0)
  await search.press('ArrowDown')
  const grain = page.getByRole('option', {name: 'Maïs grain', exact: true})
  await expect(grain).toBeFocused()
  await grain.press(' ')
  await expect(grain).toHaveAttribute('aria-selected', 'true')
  await grain.press('Escape')
  await expect(crops).toBeFocused()
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await crops.press('ArrowDown')
  await search.fill('aucune')
  await page.getByRole('option', {name: 'Aucune', exact: true}).click()
  await search.fill('')
  await expect(page.getByRole('option', {name: 'Aucune', exact: true})).toHaveAttribute('aria-selected', 'true')
  await expect(grain).toHaveAttribute('aria-selected', 'false')
  await search.fill('soja')
  await search.press('ArrowDown')
  await page.getByRole('option', {name: 'Soja', exact: true}).press('Enter')
  await search.fill('')
  await expect(page.getByRole('option', {name: 'Soja', exact: true})).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('option', {name: 'Aucune', exact: true})).toHaveAttribute('aria-selected', 'false')
  await search.press('Escape')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  expect((await requests())[0].body.data.meters[0].offSeason.crops).toEqual(['Soja'])
})

test('un ancien texte libre reste sélectionné, enregistré et lisible après l’envoi', async ({page, context}) => {
  const requests = await authenticate(context, 'legacy')
  await page.goto(responseUrl)
  const legacy = 'Mélange local : maïs, sorgho / trèfle'
  const crops = page.getByRole('button', {name: 'Cultures irriguées', exact: true}).first()
  await expect(crops).toHaveText(legacy)
  await crops.click()
  await expect(page.getByRole('option', {name: legacy, exact: true})).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('option', {name: 'Blé', exact: true}).click()
  await page.keyboard.press('Escape')
  const missingCrops = page.getByRole('group', {name: seasonNeedsTitle, exact: true}).getByRole('button', {name: 'Cultures irriguées', exact: true})
  await missingCrops.click()
  await page.getByRole('option', {name: 'Blé', exact: true}).click()
  await page.keyboard.press('Escape')
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(missingCrops).toHaveAttribute('aria-invalid', 'true')
  await expect(missingCrops).toBeFocused()
  await expect(page.getByText('Sélectionnez les cultures, ou choisissez « Aucune ».', {exact: true})).toBeVisible()
  expect(await requests()).toHaveLength(0)
  await missingCrops.click()
  await page.getByRole('option', {name: 'Blé', exact: true}).click()
  await page.keyboard.press('Escape')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  expect((await requests())[0].body.data.meters[0].offSeason.crops).toEqual([legacy, 'Blé'])
  await page.reload()
  await crops.click()
  await expect(page.getByRole('option', {name: legacy, exact: true})).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('option', {name: 'Blé', exact: true})).toHaveAttribute('aria-selected', 'true')
  await page.keyboard.press('Escape')
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  await expect(page.getByText(`${legacy}, Blé`, {exact: true})).toBeVisible()
  await expect(page.getByRole('button', {name: 'Cultures irriguées', exact: true})).toHaveCount(0)
  const writes = await requests()
  expect(writes).toHaveLength(2)
  expect(writes[1].body.data.meters[0].offSeason.crops).toEqual([legacy, 'Blé'])
})

test('usages et sous-usages restent proposés, indentés et sélectionnables sans recherche', async ({page, context}) => {
  const requests = await authenticate(context)
  await page.goto(responseUrl)
  const usage = page.getByRole('combobox', {name: 'Usage hors étiage', exact: true}).first()
  await usage.click()
  const choices = page.getByRole('listbox')
  const parent = choices.getByRole('option', {name: 'Irrigation', exact: true})
  const child = choices.getByRole('option', {name: 'Aspersion — Irrigation', exact: true})
  await expect(parent).toHaveAttribute('data-usage-level', 'parent')
  await expect(child).toHaveAttribute('data-usage-level', 'child')
  await expect(choices.getByRole('option').first()).toHaveText('Irrigation')
  const parentLabel = await parent.locator('.quick-declaration-usage-option-label').boundingBox()
  const childLabel = await child.locator('.quick-declaration-usage-option-label').boundingBox()
  expect(childLabel.x).toBeGreaterThan(parentLabel.x + 15)
  await usage.press('Enter')
  await expect(usage).toHaveValue('Irrigation')
  const secondUsage = page.getByRole('combobox', {name: 'Usage étiage', exact: true}).first()
  await secondUsage.fill('Asper')
  await expect(page.getByRole('option')).toHaveCount(1)
  await expect(child).toContainText('Irrigation')
  await secondUsage.press('Escape')
  await expect(page.getByRole('option')).toHaveCount(0)
  await secondUsage.press('ArrowDown')
  await expect(page.getByRole('option')).toHaveCount(5)
  await secondUsage.fill('Asp')
  await expect(page.getByRole('option')).toHaveCount(1)
  await secondUsage.press('Enter')
  await expect(secondUsage).toHaveValue('Aspersion')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByRole('region', {name: 'Enregistrement de la réponse', exact: true}).getByRole('status')).toHaveText('Brouillon enregistré.')
  expect((await requests())[0].body.data.meters[0]).toMatchObject({offSeason: {usageId: campaignIds.parentUsage}, season: {usageId: campaignIds.usage}})
  await page.reload()
  await expect(usage).toHaveValue('Irrigation')
  await expect(secondUsage).toHaveValue('Aspersion')
})

test('les propositions sont modifiables, enregistrables puis soumises sans données agricoles en réalimentation', async ({page, context}) => {
  const requests = await authenticate(context, 'prefill')
  await page.goto(responseUrl)
  await expect(page.getByText('Données préremplies à vérifier.', {exact: true})).toBeVisible()
  await expect(page.getByText('À compléter', {exact: true})).toBeVisible()
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveValue('10')
  await expect(page.locator('[name="meters.0.offSeason.indexEnd"]')).toHaveValue('')
  await expect(page.locator('[name="needs.offSeason.volume"]')).toHaveValue(/75\s000/)
  expect(await requests()).toHaveLength(0)

  await page.locator('[name="needs.offSeason.volume"]').fill('76000')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  await expect(page.getByText('Données préremplies à vérifier.', {exact: true})).toHaveCount(0)
  await page.reload()
  await expect(page.locator('[name="needs.offSeason.volume"]')).toHaveValue(/76\s000/)
  await page.locator('[name="meters.0.offSeason.indexEnd"]').fill('20')
  await page.locator('[name="meters.0.season.indexEnd"]').fill('30')
  for (const usage of await page.getByRole('combobox').all()) {
    await usage.fill('Remplissage')
    await page.getByRole('option', {name: 'Remplissage plan d’eau — Réalimentation d’une ressource en eau', exact: true}).click()
  }
  for (const surface of await page.locator('input[name$=".surface"]').all()) {
    await expect(surface).toHaveAttribute('aria-required', 'false')
    await surface.fill('')
  }
  await expect(page.getByRole('button', {name: 'Cultures irriguées (facultatif)', exact: true})).toHaveCount(4)
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  const writes = await requests()
  expect(writes).toHaveLength(2)
  expect(writes[1].path.endsWith('/submit')).toBe(true)
  expect(writes[1].body.data.needs.offSeason).toMatchObject({volume: '76000', usageId: campaignIds.fillingUsage, surface: '', crops: []})
  expect(writes[1].body.data.meters[0].offSeason).toMatchObject({indexStart: '10', indexEnd: '20', usageId: campaignIds.fillingUsage, surface: '', crops: []})
  expect(writes[1].body.data).not.toHaveProperty('prefill')
})

test('sans usage autorisé est une information précédente, pas une réponse ni une interdiction de demander', async ({page, context}) => {
  const requests = await authenticate(context, 'prefill-unauthorized')
  await page.goto(responseUrl)
  const notice = page.getByText('Autorisation précédente : aucun usage autorisé hors étiage.', {exact: true})
  await expect(notice).toBeVisible()
  const needs = page.getByRole('group', {name: offSeasonNeedsTitle, exact: true})
  await expect(needs.getByRole('combobox')).toHaveValue('')
  await expect(page.locator('[name="needs.offSeason.volume"]')).toHaveValue('')
  await expect(page.locator('[name="meters.0.offSeason.indexEnd"]')).toHaveValue('')
  await needs.getByRole('combobox').click()
  await needs.getByRole('combobox').fill('Remplissage')
  await page.getByRole('option', {name: /Remplissage plan d’eau/}).click()
  await page.locator('[name="needs.offSeason.volume"]').fill('5000')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  await expect(notice).toBeVisible()
  expect((await requests())[0].body.data.needs.offSeason).toMatchObject({usageId: campaignIds.fillingUsage, volume: '5000'})
})

test('changer d’usage actualise les erreurs agricoles sans effacer une surface ou des cultures saisies', async ({page, context}) => {
  const requests = await authenticate(context, 'complete')
  await page.goto(responseUrl)
  const needs = page.getByRole('group', {name: offSeasonNeedsTitle, exact: true})
  const usage = needs.getByRole('combobox')
  await usage.click()
  const parent = page.getByRole('option', {name: 'Réalimentation d’une ressource en eau', exact: true})
  const child = page.getByRole('option', {name: 'Remplissage plan d’eau — Réalimentation d’une ressource en eau', exact: true})
  await expect(parent).toHaveAttribute('data-usage-level', 'parent')
  await expect(child).toHaveAttribute('data-usage-level', 'child')
  await usage.fill('Remplissage')
  await usage.press('ArrowDown')
  await usage.press('Enter')
  await expect(usage).toHaveValue('Remplissage plan d’eau')
  await expect(page.locator('[name="needs.offSeason.surface"]')).toHaveValue('2')
  await expect(needs.getByRole('button', {name: 'Cultures irriguées (facultatif)', exact: true})).toHaveText('Maïs')
  await page.locator('[name="needs.offSeason.surface"]').fill('')
  await needs.getByRole('button', {name: 'Cultures irriguées (facultatif)', exact: true}).click()
  // Clear the historical free-text Maïs value without inventing an Aucune answer.
  await page.getByRole('option', {name: 'Maïs', exact: true}).click()
  await page.keyboard.press('Escape')
  await usage.fill('Aspersion')
  await page.getByRole('option', {name: /Aspersion/}).click()
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.locator('[name="needs.offSeason.surface"]')).toHaveAttribute('aria-invalid', 'true')
  await expect(needs.getByText('Sélectionnez les cultures, ou choisissez « Aucune ».', {exact: true})).toBeVisible()
  expect(await requests()).toHaveLength(0)
  await usage.fill('Réalimentation')
  await page.getByRole('option', {name: 'Réalimentation d’une ressource en eau', exact: true}).click()
  await expect(page.locator('[name="needs.offSeason.surface"]')).toHaveAttribute('aria-invalid', 'false')
  await expect(needs.getByText('Sélectionnez les cultures, ou choisissez « Aucune ».', {exact: true})).toHaveCount(0)
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  expect((await requests())[0].body.data.needs.offSeason).toMatchObject({usageId: campaignIds.replenishmentUsage, surface: '', crops: []})
})

test('les champs du demandeur attendent l’activation de l’interface avant d’accepter une interaction', async ({page, context}) => {
  const requests = await authenticate(context)
  const scripts = Promise.withResolvers()
  await page.route(`${frontUrl}/_next/static/**/*.js`, async route => {
    await scripts.promise
    await route.continue()
  })
  const usage = page.getByRole('combobox', {name: 'Usage hors étiage', exact: true}).first()
  try {
    await page.goto(responseUrl, {waitUntil: 'commit'})
    await expect(usage).toBeVisible()
    await expect(usage).toBeDisabled()
    await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toBeDisabled()
    await expect(page.getByRole('button', {name: 'Envoyer ma réponse', exact: true})).toBeDisabled()
    await expect(page.getByRole('option')).toHaveCount(0)
  } finally {
    scripts.resolve()
  }
  await expect(usage).toBeEnabled()
  await usage.click()
  await page.getByRole('option', {name: 'Irrigation', exact: true}).click()
  await expect(usage).toHaveValue('Irrigation')
  expect(await requests()).toHaveLength(0)
})

test('les index d’un compteur sont croissants : signalement immédiat, brouillon conservé et égalité autorisée', async ({page, context}) => {
  const requests = await authenticate(context, 'complete')
  await page.goto(responseUrl)
  const middle = page.locator('[name="meters.0.offSeason.indexEnd"]')
  const end = page.locator('[name="meters.0.season.indexEnd"]')
  await middle.fill('9')
  await middle.press('Tab')
  await expect(middle).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByText('L’index du 01/06/2026 doit être supérieur ou égal à celui du 31/10/2025.', {exact: true})).toBeVisible()
  await end.fill('8')
  await end.press('Tab')
  await expect(end).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByText('L’index du 31/10/2026 doit être supérieur ou égal à celui du 01/06/2026.', {exact: true})).toBeVisible()
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(middle).toBeFocused()
  expect(await requests()).toHaveLength(0)
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByRole('region', {name: 'Enregistrement de la réponse', exact: true}).getByRole('status')).toHaveText('Brouillon enregistré. Les index signalés restent à corriger avant l’envoi.')
  expect((await requests())[0].body.data.meters[0]).toMatchObject({offSeason: {indexStart: '10', indexEnd: '9'}, season: {indexEnd: '8'}})
  await page.reload()
  await expect(middle).toHaveValue('9')
  await expect(end).toHaveValue('8')
  await middle.fill('10')
  await end.fill('10')
  await end.press('Tab')
  await expect(middle).toHaveAttribute('aria-invalid', 'false')
  await expect(end).toHaveAttribute('aria-invalid', 'false')
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  const writes = await requests()
  expect(writes).toHaveLength(2)
  expect(writes[1].path.endsWith('/submit')).toBe(true)
  expect(writes[1].body.data.meters[0]).toMatchObject({offSeason: {indexStart: '10', indexEnd: '10'}, season: {indexEnd: '10'}})
})

test('la carte est affichée dès l’ouverture et n’est pas recréée pendant la saisie', async ({page, context}, testInfo) => {
  const requests = await authenticate(context, 'map')
  await page.goto(responseUrl)
  const map = page.getByRole('region', {name: 'Localisation du point de prélèvement', exact: true})
  await expect(map).toBeVisible()
  await expect(page.getByRole('button', {name: /Afficher la carte|Voir la carte/})).toHaveCount(0)
  const mapSurface = map.locator('canvas, [data-map-unavailable]')
  await expect(mapSurface).toBeVisible()
  const originalSurface = await mapSurface.elementHandle()
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('123')
  await page.locator('[name="meters.0.offSeason.indexEnd"]').fill('124')
  expect(await originalSurface.evaluate(element => element.isConnected)).toBe(true)
  expect(await requests()).toHaveLength(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await map.screenshot({path: testInfo.outputPath('carte-campagne-visible.png')})
})

test('retirer un compteur saisi ne mélange pas le numéro, les relevés et les usages du suivant', async ({page, context}) => {
  const requests = await authenticate(context, 'missing')
  await page.goto(responseUrl)
  await page.getByLabel('Numéro du compteur', {exact: true}).fill('SAISIE-001')
  await page.getByRole('combobox', {name: 'Usage hors étiage', exact: true}).first().fill('Aspersion')
  await page.getByRole('option', {name: /Aspersion/}).click()
  await page.getByRole('button', {name: 'Ajouter un compteur', exact: true}).click()
  await page.getByLabel('Numéro du compteur', {exact: true}).nth(1).fill('SAISIE-002')
  await page.locator('[name="meters.1.offSeason.indexStart"]').fill('50')
  await page.getByRole('combobox', {name: 'Usage hors étiage', exact: true}).nth(1).fill('Goutte')
  await page.getByRole('option', {name: /Goutte-à-goutte/}).click()
  await page.getByRole('button', {name: 'Retirer ce compteur', exact: true}).first().click()
  await expect(page.getByLabel('Numéro du compteur', {exact: true})).toHaveValue('SAISIE-002')
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveValue('50')
  await expect(page.getByRole('combobox', {name: 'Usage hors étiage', exact: true}).first()).toHaveValue('Goutte-à-goutte')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  expect((await requests())[0].body.data.meters).toMatchObject([{serialNumber: 'SAISIE-002', offSeason: {indexStart: '50', usageId: campaignIds.secondUsage}}])
})

test('les erreurs métier de l’API et les champs invalides restent lisibles sans effacer la saisie', async ({page, context}) => {
  await authenticate(context, 'closed')
  await page.goto(responseUrl)
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('12')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText(/Cette campagne n’est pas ouverte à la saisie/)).toBeVisible()
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveValue('12')
  await authenticate(context, 'invalid')
  page.once('dialog', dialog => dialog.accept())
  await page.reload()
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('15')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Le relevé du compteur doit être vérifié.', {exact: true})).toBeVisible()
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveAttribute('aria-invalid', 'true')
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveValue('15')
})

test('collecteur : navigation conditionnelle, résultats envoyés, lecture seule et export complet', async ({page, context, isMobile}) => {
  const requests = await authenticate(context, 'collector')
  await page.goto(`${frontUrl}/campagnes/${campaignIds.campaign}`)
  if (isMobile) await page.getByRole('button', {name: 'Menu', exact: true}).click()
  await expect(page.getByRole('link', {name: 'Campagnes', exact: true})).toBeVisible()
  if (isMobile) await page.getByRole('button', {name: 'Fermer', exact: true}).click()
  await page.getByRole('button', {name: 'Résultats envoyés', exact: true}).click()
  await expect(page.getByText('120 m³', {exact: true})).toBeVisible()
  await expect(page.getByRole('heading', {name: 'Volumes prélevés calculés', exact: true})).toBeVisible()
  await expect(page.getByText('0 m³', {exact: true}).first()).toBeVisible()
  await expect(page.getByText('En attente de publication', {exact: true})).toBeVisible()
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', {name: 'Exporter tous les résultats (CSV)', exact: true}).click()
  expect((await downloaded).suggestedFilename()).toBe('resultats-campagne.csv')
  expect((await requests())[0].path.endsWith('/export')).toBe(true)
  await page.getByRole('link', {name: 'Consulter', exact: true}).click()
  await expect(page.locator('[name="needs.season.volume"]')).toHaveValue('120')
  await expect(page.locator('[name="needs.season.volume"]')).toHaveAttribute('readonly', '')
  await expect(page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true})).toHaveCount(0)
  await expect(page.getByRole('button', {name: 'Modifier ma réponse', exact: true})).toHaveCount(0)
})

test('admin : sélection groupée locale puis création du brouillon', async ({page, context}) => {
  const requests = await authenticate(context, 'admin')
  await page.goto(`${frontUrl}/administration/campagnes/nouvelle`)
  await page.getByLabel('Nom de la campagne', {exact: true}).fill('Collecte de test')
  await page.getByLabel('Collecteur destinataire', {exact: true}).selectOption(campaignIds.collector)
  await page.getByRole('button', {name: 'Sélectionner les 1 résultats', exact: true}).click()
  await expect(page.getByText('1 exploitation sélectionnée', {exact: true})).toBeVisible()
  await page.getByRole('button', {name: 'Tout désélectionner', exact: true}).click()
  expect(await requests()).toEqual([])
  await page.getByRole('checkbox', {name: /Point synthétique/}).check()
  await page.getByRole('button', {name: 'Créer le brouillon', exact: true}).click()
  await expect(page).toHaveURL(`${frontUrl}/administration/campagnes/${campaignIds.campaign}`)
  const writes = await requests()
  expect(writes).toHaveLength(1)
  expect(writes[0].body).toMatchObject({opensOn: null, closesOn: null, exploitationIds: [campaignIds.exploitation], collecteurUserId: campaignIds.collector})
})

test('avant le dernier relevé, le bouton d’envoi signale les champs invalides et le brouillon reste possible', async ({page, context}) => {
  const requests = await authenticate(context, 'before')
  await page.clock.setFixedTime(new Date('2026-09-24T12:00:00Z'))
  await page.goto(responseUrl)
  const submit = page.getByRole('button', {name: 'Envoyer ma réponse', exact: true})
  await expect(submit).toBeEnabled()
  await expect(page.getByText(/Le bilan pourra être envoyé à partir du 31 octobre 2026/)).toBeVisible()
  await submit.click()
  const start = page.locator('[name="meters.0.offSeason.indexStart"]')
  await expect(start).toBeFocused()
  await expect(start).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByRole('button', {name: /Voir les champs à corriger/})).toBeVisible()
  expect(await requests()).toHaveLength(0)
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('5')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  expect((await requests())[0].method).toBe('PUT')
})

test('une réponse complète avant le 31 octobre explique le blocage sans requête d’envoi', async ({page, context}) => {
  const requests = await authenticate(context, 'before-complete')
  await page.clock.setFixedTime(new Date('2026-09-24T12:00:00Z'))
  await page.goto(responseUrl)
  const submit = page.getByRole('button', {name: 'Envoyer ma réponse', exact: true})
  await expect(submit).toBeEnabled()
  await submit.click()
  const feedback = page.getByRole('region', {name: 'Enregistrement de la réponse', exact: true})
  await expect(feedback.getByRole('alert')).toHaveText('Le bilan pourra être envoyé à partir du 31 octobre 2026. Vous pouvez enregistrer un brouillon.')
  await expect(page.locator('form [aria-invalid="true"]')).toHaveCount(0)
  expect(await requests()).toHaveLength(0)
  await feedback.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(feedback.getByRole('status')).toHaveText('Brouillon enregistré.')
  expect((await requests())[0].method).toBe('PUT')
})

test('admin : la part hors campagne est conservée, validation à 100 % et confirmation explicite', async ({page, context}) => {
  const requests = await authenticate(context, 'admin-review')
  await page.goto(`${frontUrl}/administration/campagnes/${campaignIds.campaign}/reponses/${campaignIds.response}`)
  await page.getByRole('button', {name: 'Vérifier le compteur SYNTH-M1', exact: true}).click()
  await expect(page.getByText(/Part hors campagne — conservée dans la répartition/)).toBeVisible()
  const approve = page.getByRole('button', {name: 'Valider et publier les volumes', exact: true})
  await expect(approve).toBeDisabled()
  const off = page.getByLabel('Part hors étiage 2025–2026 (%)', {exact: true})
  const season = page.getByLabel('Part étiage 2026 (%)', {exact: true})
  await off.nth(0).fill('70')
  await off.nth(1).fill('20')
  await season.nth(0).fill('70')
  await season.nth(1).fill('30')
  await page.getByRole('checkbox', {name: /Je confirme que ces rattachements/}).check()
  await expect(approve).toBeDisabled()
  await off.nth(1).fill('30')
  await approve.click()
  await expect(page.getByRole('heading', {name: 'Rattachement et répartition validés. Les volumes sont publiés.', exact: true})).toBeVisible()
  const writes = await requests()
  expect(writes).toHaveLength(1)
  expect(writes[0].body).toMatchObject({expectedHash: '1'.repeat(64), confirmHistorical: true})
  expect(writes[0].body.allocations.map(row => row.offSeasonPercentage)).toEqual(['70', '30'])
})

test('la vérification du compteur attend l’activation de l’interface avant d’accepter un clic', async ({page, context}) => {
  await authenticate(context, 'admin-review')
  const scripts = Promise.withResolvers()
  await page.route(`${frontUrl}/_next/static/**/*.js`, async route => {
    await scripts.promise
    await route.continue()
  })
  const verify = page.getByRole('button', {name: 'Vérifier le compteur SYNTH-M1', exact: true})
  try {
    await page.goto(`${frontUrl}/administration/campagnes/${campaignIds.campaign}/reponses/${campaignIds.response}`, {waitUntil: 'commit'})
    await expect(verify).toBeVisible()
    await expect(verify).toBeDisabled()
  } finally {
    scripts.resolve()
  }
  await expect(verify).toBeEnabled()
  await verify.click()
  await expect(page.getByRole('region', {name: 'Vérification du compteur SYNTH-M1', exact: true})).toBeVisible()
  await expect(page.getByText(/Part hors campagne — conservée dans la répartition/)).toBeVisible()
})

test('la déclaration générée distingue ses compteurs et renvoie vers la réponse de campagne', async ({page, context}) => {
  await authenticate(context)
  await page.goto(`${frontUrl}/mes-declarations/${campaignIds.declaration}`)
  await expect(page.getByText('Compteur : SYNTH-M1', {exact: true})).toBeVisible()
  await expect(page.getByText('Compteur : SYNTH-M2', {exact: true})).toBeVisible()
  await expect(page.getByRole('link', {name: 'Consulter la réponse et les volumes calculés', exact: true})).toHaveAttribute('href', `/campagnes/${campaignIds.campaign}/reponses/${campaignIds.response}`)
  await page.getByText('Voir les derniers index connus', {exact: true}).first().click()
  await expect(page.getByRole('columnheader', {name: 'Compteur', exact: true}).first()).toBeVisible()
  await expect(page.getByRole('cell', {name: 'SYNTH-M1', exact: true})).toBeVisible()
})

test('le reçu conserve la notice pour l’instructeur et oriente l’admin vers la gestion de campagne', async ({page, context}) => {
  await authenticate(context, 'instructor')
  await page.goto(`${frontUrl}/declarations/synthetic-source`)
  await expect(page.getByText('Ces index proviennent d’une campagne.', {exact: true})).toBeVisible()
  await expect(page.getByRole('link', {name: 'Consulter la réponse et les volumes calculés', exact: true})).toHaveCount(0)
  await authenticate(context, 'admin')
  await page.reload()
  await expect(page.getByRole('link', {name: 'Consulter la réponse et les volumes calculés', exact: true})).toHaveAttribute('href', `/administration/campagnes/${campaignIds.campaign}/reponses/${campaignIds.response}`)
})
