import {randomUUID} from 'node:crypto'

import {expect, test} from '@playwright/test'
import {encode} from 'next-auth/jwt'

import {campaignIds} from '../../.github/scripts/campaign-fixtures.mjs'

const frontUrl = 'https://127.0.0.1:3443'
test.use({ignoreHTTPSErrors: true, reducedMotion: 'reduce'})

test.beforeEach(async ({page}) => {
  await page.route('**/*', route => [frontUrl, 'http://127.0.0.1:3417'].includes(new URL(route.request().url()).origin) ? route.continue() : route.abort())
  await page.clock.setFixedTime(new Date('2026-11-01T12:00:00Z'))
})

async function authenticate(context, role = 'preleveur', sessionId = randomUUID()) {
  const apiToken = `browser-test-campaign-${role}-${sessionId}`
  const token = await encode({secret: 'browser-tests-only-never-a-real-secret', token: {
    sub: campaignIds.user, token: apiToken, role: role.startsWith('admin') ? 'ADMIN' : role === 'instructor' ? 'INSTRUCTOR' : 'DECLARANT', permissions: [],
    declarantRole: role.startsWith('collector') ? 'COLLECTEUR' : 'PRELEVEUR',
    apiExpiresAt: new Date(Date.now() + 3_600_000).toISOString(), infoRefreshedAt: Date.now(),
    userInfo: {id: campaignIds.user, email: 'campaign@example.test', declarantRole: role.startsWith('collector') ? 'COLLECTEUR' : 'PRELEVEUR'}
  }, maxAge: 3600})
  await context.addCookies(['next-auth.session-token', '__Secure-next-auth.session-token'].map(name => ({name, value: token, url: frontUrl, httpOnly: true, secure: true, sameSite: 'Lax'})))
  return async () => (await context.request.get('http://127.0.0.1:3431/api/__campaign-requests', {headers: {authorization: `Bearer ${apiToken}`}})).json()
}

const responseUrl = `${frontUrl}/campagnes/${campaignIds.campaign}/reponses/${campaignIds.response}`
const seasonNeedsTitle = 'Demande étiage du 1er juin au 31 octobre 2027'
const offSeasonNeedsTitle = 'Demande hors-étiage du 1er novembre 2027 au 31 mai 2028'

test('deux compteurs : brouillon incomplet, reprise, envoi et modification sans nouvelle déclaration client', async ({page, context}, testInfo) => {
  const requests = await authenticate(context)
  await page.goto(responseUrl)
  await expect(page.getByRole('heading', {name: /Code compteur Agence de l’eau : 001/})).toBeVisible()
  await expect(page.getByRole('heading', {name: 'Numéro de série du compteur : SYNTH-M1', exact: true})).toBeVisible()
  await expect(page.getByRole('heading', {name: 'Numéro de série du compteur : SYNTH-M2', exact: true})).toBeVisible()
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('123')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  const saveFeedback = page.getByRole('region', {name: 'Enregistrement de la réponse', exact: true}).getByRole('status')
  await expect(saveFeedback).toHaveText('Brouillon enregistré.')
  await expect(saveFeedback).toBeInViewport()
  await page.reload()
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveValue('123')
  await expect(page.locator('[name="meters.1.offSeason.indexStart"]')).toHaveValue('')
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Vérifiez les champs signalés avant d’envoyer votre réponse.', {exact: true})).toBeVisible()
  expect((await requests()).length).toBe(1)
  for (const input of await page.locator('form input[inputmode="decimal"]').all()) await input.fill('0')
  for (const crops of await page.getByRole('button', {name: 'Cultures irriguées', exact: true}).all()) {
    await crops.click()
    await page.getByRole('option', {name: 'Aucune', exact: true}).click()
    await page.keyboard.press('Escape')
  }
  for (const usage of await page.getByRole('combobox').all()) {
    await usage.click()
    await usage.fill('Aspersion')
    await page.getByRole('option', {name: /Aspersion/}).click()
  }
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  await expect(page.getByRole('heading', {name: 'Volumes prélevés calculés', exact: true})).toBeVisible()
  await expect(page.locator('dd').filter({hasText: /^0 m³$/})).toHaveCount(3)
  await expect(page.getByText(/volumes en attente de vérification/i)).toHaveCount(0)
  const writes = await requests()
  expect(writes).toHaveLength(2)
  expect(writes[1].body.revision).toBe(1)
  expect(writes[1].body.data.meters.map(meter => meter.compteurId)).toEqual([campaignIds.meter, campaignIds.secondMeter])
  expect(writes[1].body.data.meters.map(meter => [meter.offSeason.crops, meter.season.crops])).toEqual([[['Aucune'], ['Aucune']], [['Aucune'], ['Aucune']]])
  expect(writes[1].body.data.needs).toMatchObject({season: {crops: ['Aucune']}, offSeason: {crops: ['Aucune']}})
  expect(writes[1].path.endsWith('/submit')).toBe(true)
  await expect(page.getByRole('button', {name: 'Cultures irriguées', exact: true})).toHaveCount(0)
  await page.getByRole('button', {name: 'Modifier ma réponse', exact: true}).click()
  await page.locator('[name="needs.season.volume"]').fill('20')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Ces modifications ne sont pas encore envoyées.', {exact: true})).toBeVisible()
  await expect(page.getByText('L’OUGC peut aussi compléter cette réponse et consulter le brouillon enregistré.', {exact: true})).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({path: testInfo.outputPath('formulaire-campagne.png'), fullPage: true})
})

test('numéro absent et conflit : la saisie est conservée, aucune valeur inventée', async ({page, context}) => {
  const requests = await authenticate(context, 'missing-conflict')
  await page.goto(responseUrl)
  await expect(page.getByRole('textbox', {name: 'Numéro de série du compteur', exact: true})).toHaveValue('')
  await page.getByRole('textbox', {name: 'Numéro de série du compteur', exact: true}).fill('MANUEL-001')
  await expect(page.getByText('Nous n’avons pas le numéro de série de votre compteur. Pouvez-vous le renseigner ici', {exact: true})).toBeVisible()
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('0')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText(/La réponse a été modifiée/)).toBeVisible()
  await expect(page.getByRole('textbox', {name: 'Numéro de série du compteur', exact: true})).toHaveValue('MANUEL-001')
  expect((await requests())[0].body.data.meters[0].compteurId).toBeNull()
})

test('le numéro est obligatoire à l’envoi, les brouillons incomplets et les vrais zéros sont conservés', async ({page, context}) => {
  const requests = await authenticate(context, 'missing')
  await page.goto(responseUrl)
  await expect(page.getByRole('heading', {name: 'Déclarer mes prélèvements et mes besoins', exact: true})).toBeVisible()
  const serial = page.getByRole('textbox', {name: 'Numéro de série du compteur', exact: true})
  await expect(page.getByRole('button', {name: 'Ajouter un compteur', exact: true})).toHaveCount(0)
  await expect(page.locator('[name$=".indexStart"]')).toHaveCount(1)
  await expect(serial).toHaveValue('')
  await expect(serial).toHaveAttribute('aria-required', 'true')
  await expect(page.getByText('Nous n’avons pas le numéro de série de votre compteur. Pouvez-vous le renseigner ici', {exact: true})).toBeVisible()
  const index = page.getByRole('textbox', {name: 'Index au 01/11/2025', exact: true})
  await expect(index).toHaveValue('')
  await expect(index).not.toHaveAttribute('placeholder')
  await expect(index).toHaveAttribute('aria-required', 'true')
  await expect(page.locator('label[for="campaign-meters-0-offSeason-indexStart"]')).toHaveText('Index au 01/11/2025 *')
  await expect(page.getByText('Choisissez une ou plusieurs cultures. Si vous ne savez pas encore, choisissez seulement la famille (par exemple : céréales).', {exact: true}).first()).toBeVisible()
  const details = page.getByRole('heading', {name: 'Préleveur', exact: true})
  expect(await details.evaluate(element => Boolean(document.querySelector('form').compareDocumentPosition(element) & Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true)
  for (const input of await page.locator('form input[inputmode="decimal"]').all()) await input.fill('0')
  for (const crops of await page.getByRole('button', {name: 'Cultures irriguées', exact: true}).all()) {
    await crops.click()
    await page.getByRole('option', {name: 'Aucune', exact: true}).click()
    await page.keyboard.press('Escape')
  }
  for (const usage of await page.getByRole('combobox').all()) {
    await usage.click()
    await expect(page.locator('[data-usage-selection-indicator]')).toHaveCount(await page.getByRole('option').count())
    await expect(page.getByRole('option').locator('[style*="background-color"]')).toHaveCount(0)
    await page.getByRole('option', {name: /Aspersion/}).click()
  }
  await expect(index).toHaveValue('0')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(serial).toBeFocused()
  await expect(page.getByText('Renseignez le numéro de série du compteur.', {exact: true})).toBeVisible()
  expect(await requests()).toHaveLength(1)
  await serial.fill('MANUEL-001')
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  const writes = await requests()
  expect(writes).toHaveLength(2)
  expect(writes[1].path).toBe(`/api/campaigns/${campaignIds.campaign}/responses/${campaignIds.response}/submit`)
  expect(writes[1].body.data.meters[0]).toMatchObject({compteurId: null, serialNumber: 'MANUEL-001', offSeason: {indexStart: '0', indexEnd: '0'}, season: {indexEnd: '0'}})
  await page.reload()
  await expect(serial).toHaveValue('MANUEL-001')
  await expect(index).toHaveValue('0')
})

for (const sourceSerial of [null, 'SYNTH-SOURCE-001']) {
  test(`un index proposé sans compteur identifié reste modifiable et peut être envoyé ${sourceSerial ? 'avec le numéro source' : 'après renseignement du numéro manquant'}`, async ({page, context}) => {
    const requests = await authenticate(context, sourceSerial ? 'prefill-missing-serial' : 'prefill-missing')
    const draftSerial = sourceSerial ? 'SYNTH-CORRECTED-001' : null
    const submittedSerial = draftSerial || 'MANUEL-001'
    await page.goto(responseUrl)
    const index = page.getByRole('textbox', {name: 'Index au 01/11/2025', exact: true})
    const serial = page.getByRole('textbox', {name: 'Numéro de série du compteur', exact: true})
    await expect(page.getByText('Données préremplies à vérifier.', {exact: true})).toBeVisible()
    await expect(page.getByText('À compléter', {exact: true})).toBeVisible()
    await expect(index).toHaveValue(/144\s413/)
    await expect(serial).toHaveValue(sourceSerial || '')
    const unknownSerialHint = page.getByText('Nous n’avons pas le numéro de série de votre compteur. Pouvez-vous le renseigner ici', {exact: true})
    await expect(unknownSerialHint).toHaveCount(sourceSerial ? 0 : 1)
    await expect(page.locator('[name$=".indexStart"]')).toHaveCount(1)
    await expect(page.getByRole('button', {name: 'Ajouter un compteur', exact: true})).toHaveCount(0)
    expect(await requests()).toHaveLength(0)
    await index.fill('144414')
    if (sourceSerial) {
      await serial.fill(submittedSerial)
      await expect(unknownSerialHint).toHaveCount(0)
    }
    await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
    await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
    expect((await requests())[0]).toMatchObject({method: 'PUT', path: `/api/campaigns/${campaignIds.campaign}/responses/${campaignIds.response}`})
    expect((await requests())[0].body).toMatchObject({revision: 0, data: {meters: [{compteurId: null, serialNumber: draftSerial, offSeason: {indexStart: '144414'}}]}})
    await page.reload()
    await expect(index).toHaveValue(/144\s414/)
    await expect(serial).toHaveValue(draftSerial || '')
    await expect(page.getByText('Données préremplies à vérifier.', {exact: true})).toHaveCount(0)
    await page.getByRole('textbox', {name: 'Index au 31/05/2026', exact: true}).fill('144500')
    await page.getByRole('textbox', {name: 'Index au 31/10/2026', exact: true}).fill('144600')
    for (const input of await page.locator('form input[inputmode="decimal"]:not([name*=".index"])').all()) await input.fill('0')
    for (const usage of await page.getByRole('combobox').all()) {
      await usage.click()
      await usage.fill('Remplissage')
      await page.getByRole('option', {name: /Remplissage plan d’eau/}).click()
    }
    if (!sourceSerial) await serial.fill(submittedSerial)
    await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
    await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
    const writes = await requests()
    expect(writes).toHaveLength(2)
    expect(writes[1].path).toBe(`/api/campaigns/${campaignIds.campaign}/responses/${campaignIds.response}/submit`)
    expect(writes[1].body.revision).toBe(1)
    expect(writes[1].body.data.meters).toMatchObject([{compteurId: null, serialNumber: submittedSerial, offSeason: {indexStart: '144414', indexEnd: '144500'}, season: {indexEnd: '144600'}}])
    await page.reload()
    await expect(index).toHaveValue(/144\s414/)
    await expect(index).toHaveAttribute('readonly', '')
    await expect(serial).toHaveValue(submittedSerial || '')
  })
}

test('Mon activité ouvre directement la réponse unique, avec un retour clair et sans filtres', async ({page, context}, testInfo) => {
  await authenticate(context)
  await page.goto(`${frontUrl}/tableau-de-bord`)
  const invitation = page.getByRole('region', {name: 'Déclarer mes prélèvements et mes besoins', exact: true})
  await expect(invitation).toBeVisible()
  await expect(invitation).not.toContainText(/exploitation/i)
  await expect(page.getByRole('heading', {name: 'Autres déclarations', exact: true})).toHaveCount(0)
  await expect(page.getByRole('link', {name: 'Nouvelle déclaration', exact: true})).toHaveCount(0)
  await expect(invitation).toContainText('Bilan de campagne 2026-2027 et recensement des besoins 2027-2028')
  await expect(invitation).toContainText('0 point déclaré sur 1')
  await page.screenshot({path: testInfo.outputPath('mon-activite-campagne.png'), fullPage: true})
  await invitation.getByRole('link', {name: 'Commencer ma déclaration', exact: true}).click()
  await expect(page).toHaveURL(responseUrl)
  await expect(page.getByRole('searchbox')).toHaveCount(0)
  await expect(page.getByText(/Vous pouvez préparer votre réponse en brouillon/)).toHaveCount(0)
  await page.getByRole('link', {name: 'Mon activité', exact: true}).last().click()
  await expect(page).toHaveURL(`${frontUrl}/tableau-de-bord`)
})

test('plusieurs comptages : une liste simple sans recherche, sans confondre deux réponses du même point', async ({page, context}) => {
  await authenticate(context, 'multiple')
  await page.goto(`${frontUrl}/campagnes/${campaignIds.campaign}`)
  await expect(page.getByText(/Code compteur Agence de l’eau : 001/)).toBeVisible()
  await expect(page.getByText(/Code compteur Agence de l’eau : 002/)).toBeVisible()
  await expect(page.getByText('Commune de test · Parcelle du moulin', {exact: true})).toHaveCount(2)
  await expect(page.getByRole('searchbox')).toHaveCount(0)
  await expect(page.getByRole('button', {name: 'Filtrer', exact: true})).toHaveCount(0)
  await expect(page.getByRole('main')).not.toContainText(/exploitation/i)
  await page.locator(`a[href="/campagnes/${campaignIds.campaign}/reponses/${campaignIds.response}"]`).click()
  await expect(page).toHaveURL(responseUrl)
})

test('une collecte clôturée ouvre la réponse en lecture seule avec une explication', async ({page, context}) => {
  const requests = await authenticate(context, 'ended')
  await page.goto(`${frontUrl}/tableau-de-bord`)
  const invitation = page.getByRole('region', {name: 'Déclarer mes prélèvements et mes besoins', exact: true})
  await expect(invitation).toContainText('0 point déclaré sur 1')
  await invitation.getByRole('link', {name: 'Consulter ma déclaration', exact: true}).click()
  await expect(page).toHaveURL(responseUrl)
  await expect(page.getByText('Cette collecte est clôturée. Votre réponse reste consultable.', {exact: true})).toBeVisible()
  await expect(page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true})).toHaveCount(0)
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveAttribute('readonly', '')
  expect(await requests()).toHaveLength(0)
})

test('un refus de permission reste compréhensible et conserve les valeurs saisies', async ({page, context}) => {
  const requests = await authenticate(context, 'forbidden')
  await page.goto(responseUrl)
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('12')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByRole('main')).not.toContainText('INSUFFICIENT_PERMISSIONS')
  await expect(page.getByText(/Vous n’avez pas les droits/)).toBeVisible()
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveValue('12')
  expect(await requests()).toHaveLength(1)
})

test('les volumes acceptent la virgule et les milliers, les usages se sélectionnent au clavier', async ({page, context}) => {
  const requests = await authenticate(context)
  await page.goto(responseUrl)
  const volume = page.locator('[name="needs.season.volume"]')
  await volume.fill('12 345,67')
  await expect(volume).toHaveValue(/12\s345,67/)
  const usage = page.getByRole('group', {name: seasonNeedsTitle, exact: true}).getByRole('combobox')
  await usage.fill('Asper')
  await usage.press('ArrowDown')
  await usage.press('Enter')
  await expect(page.getByRole('option')).toHaveCount(0)
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  const writes = await requests()
  expect(writes[0].body.data.needs.season.volume).toBe('12345.67')
  expect(writes[0].body.data.needs.season.usageId).toBe(campaignIds.usage)
  await page.reload()
  await expect(volume).toHaveValue(/12\s345,67/)
})

test('les périodes des besoins gardent leurs dates et couleurs, les catégories et cultures se sélectionnent indépendamment', async ({page, context}) => {
  const requests = await authenticate(context)
  await page.goto(responseUrl)
  const seasonNeeds = page.getByRole('group', {name: seasonNeedsTitle, exact: true})
  const offSeasonNeeds = page.getByRole('group', {name: offSeasonNeedsTitle, exact: true})
  const periodColours = await page.evaluate(() => {
    const probe = document.createElement('span')
    document.body.append(probe)
    const values = Object.fromEntries(['background-alt-yellow-tournesol', 'border-plain-yellow-tournesol', 'background-alt-blue-cumulus', 'border-plain-blue-cumulus'].map(token => {
      probe.style.color = `var(--${token})`
      return [token, getComputedStyle(probe).color]
    }))
    probe.remove()
    return values
  })
  expect(periodColours['background-alt-yellow-tournesol']).not.toBe(periodColours['background-alt-blue-cumulus'])
  expect(periodColours['border-plain-yellow-tournesol']).not.toBe(periodColours['border-plain-blue-cumulus'])
  await expect(seasonNeeds).toHaveCSS('background-color', periodColours['background-alt-yellow-tournesol'])
  await expect(seasonNeeds).toHaveCSS('border-top-color', periodColours['border-plain-yellow-tournesol'])
  await expect(offSeasonNeeds).toHaveCSS('background-color', periodColours['background-alt-blue-cumulus'])
  await expect(offSeasonNeeds).toHaveCSS('border-top-color', periodColours['border-plain-blue-cumulus'])
  await expect(page.getByRole('group', {name: 'Étiage 2026', exact: true}).first()).toHaveCSS('background-color', periodColours['background-alt-yellow-tournesol'])
  await expect(page.getByRole('group', {name: 'Hors étiage 2025–2026', exact: true}).first()).toHaveCSS('background-color', periodColours['background-alt-blue-cumulus'])
  expect(await seasonNeeds.evaluate(element => element.nextElementSibling?.querySelector('legend')?.textContent)).toBe(offSeasonNeedsTitle)
  const crops = seasonNeeds.getByRole('button', {name: 'Cultures irriguées', exact: true})
  await crops.click()
  const choices = page.getByRole('listbox', {name: 'Cultures irriguées', exact: true})
  await expect(choices).toHaveAttribute('aria-multiselectable', 'true')
  await expect(choices).toHaveAttribute('aria-required', 'true')
  await expect(choices.locator('[data-selection-indicator="checkbox"]')).toHaveCount(await choices.getByRole('option').count())
  const parent = choices.getByRole('option', {name: 'Céréales', exact: true})
  const child = choices.getByRole('option', {name: 'Maïs grain', exact: true})
  const parentLabel = parent.locator('[data-crop-level="parent"]')
  const childLabel = child.locator('[data-crop-level="child"]')
  await expect(parentLabel).toBeVisible()
  await expect(childLabel).toBeVisible()
  expect((await childLabel.boundingBox()).x).toBeGreaterThan((await parentLabel.boundingBox()).x + 15)
  await parent.click()
  await expect(parent).toHaveAttribute('aria-selected', 'true')
  await expect(parent.locator('[data-selection-indicator="checkbox"]')).toHaveAttribute('data-checked', 'true')
  await expect(child).toHaveAttribute('aria-selected', 'false')
  await expect(child.locator('[data-selection-indicator="checkbox"]')).toHaveAttribute('data-checked', 'false')
  await child.click()
  await choices.getByRole('option', {name: 'Oléagineux', exact: true}).click()
  await expect(parent).toHaveAttribute('aria-selected', 'true')
  await expect(child).toHaveAttribute('aria-selected', 'true')
  await expect(choices.getByRole('option', {name: 'Blé', exact: true})).toHaveAttribute('aria-selected', 'false')
  await page.keyboard.press('Escape')
  await expect(crops).toBeFocused()
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  expect((await requests())[0].body.data.needs).toMatchObject({season: {crops: ['Céréales', 'Maïs grain', 'Oléagineux']}, offSeason: {crops: []}})
  await page.reload()
  await crops.click()
  for (const name of ['Céréales', 'Maïs grain', 'Oléagineux']) await expect(choices.getByRole('option', {name, exact: true})).toHaveAttribute('aria-selected', 'true')
  await expect(choices.getByRole('option', {name: 'Blé', exact: true})).toHaveAttribute('aria-selected', 'false')
  await page.keyboard.press('Escape')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
})

test('le menu des cultures reste cliquable au-dessus de la barre d’enregistrement', async ({page, context}) => {
  const requests = await authenticate(context)
  await page.goto(responseUrl)
  const crops = page.getByRole('button', {name: 'Cultures irriguées', exact: true}).first()
  await expect(crops).toBeEnabled()
  await crops.scrollIntoViewIfNeeded()
  await crops.evaluate(element => window.scrollBy(0, element.getBoundingClientRect().bottom - (window.innerHeight - 260)))
  await crops.click()
  const popup = page.locator('.grouped-multiselect-popup')
  const toolbar = page.getByRole('region', {name: 'Enregistrement de la réponse', exact: true})
  await expect(popup).toBeVisible()
  await expect(toolbar).toBeInViewport()
  const menuBounds = await popup.boundingBox()
  const toolbarBounds = await toolbar.boundingBox()
  const left = Math.max(menuBounds.x, toolbarBounds.x)
  const right = Math.min(menuBounds.x + menuBounds.width, toolbarBounds.x + toolbarBounds.width)
  const top = Math.max(menuBounds.y, toolbarBounds.y)
  const bottom = Math.min(menuBounds.y + menuBounds.height, toolbarBounds.y + toolbarBounds.height)
  expect(right).toBeGreaterThan(left)
  expect(bottom).toBeGreaterThan(top)
  const point = {x: (left + right) / 2, y: (top + bottom) / 2}
  expect(await popup.evaluate((element, {x, y}) => element.contains(document.elementFromPoint(x, y)), point)).toBe(true)
  await page.mouse.click(point.x, point.y)
  await expect(page.getByRole('option', {selected: true})).toHaveCount(1)
  expect(await requests()).toHaveLength(0)
  await page.keyboard.press('Escape')
  await expect(crops).toBeFocused()
  await expect(popup).toHaveCount(0)
  await expect(toolbar.getByRole('button', {name: 'Enregistrer le brouillon', exact: true})).toBeVisible()
})

test('la recherche des cultures fonctionne au clavier et Aucune exclut les autres choix', async ({page, context}) => {
  const requests = await authenticate(context)
  await page.goto(responseUrl)
  const crops = page.getByRole('button', {name: 'Cultures irriguées', exact: true}).first()
  await expect(crops).toBeEnabled()
  await crops.focus()
  await crops.press('Enter')
  const search = page.getByRole('textbox', {name: 'Rechercher dans cultures irriguées', exact: true})
  await expect(search).toBeFocused()
  await search.fill('mais grain')
  await expect(page.getByRole('option')).toHaveCount(1)
  await search.press('Enter')
  expect(await requests()).toHaveLength(0)
  await search.press('ArrowDown')
  const grain = page.getByRole('option', {name: 'Maïs grain', exact: true})
  await expect(grain).toBeFocused()
  await grain.press(' ')
  await expect(grain).toHaveAttribute('aria-selected', 'true')
  await grain.press('Escape')
  await expect(crops).toBeFocused()
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await crops.press('ArrowDown')
  await search.fill('aucune')
  await page.getByRole('option', {name: 'Aucune', exact: true}).click()
  await search.fill('')
  await expect(page.getByRole('option', {name: 'Aucune', exact: true})).toHaveAttribute('aria-selected', 'true')
  await expect(grain).toHaveAttribute('aria-selected', 'false')
  await search.fill('soja')
  await search.press('ArrowDown')
  await page.getByRole('option', {name: 'Soja', exact: true}).press('Enter')
  await search.fill('')
  await expect(page.getByRole('option', {name: 'Soja', exact: true})).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('option', {name: 'Aucune', exact: true})).toHaveAttribute('aria-selected', 'false')
  await search.press('Escape')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  expect((await requests())[0].body.data.meters[0].offSeason.crops).toEqual(['Soja'])
})

test('un ancien texte libre reste sélectionné, enregistré et lisible après l’envoi', async ({page, context}) => {
  const requests = await authenticate(context, 'legacy')
  await page.goto(responseUrl)
  const legacy = 'Mélange local : maïs, sorgho / trèfle'
  const crops = page.getByRole('button', {name: 'Cultures irriguées', exact: true}).first()
  await expect(crops).toHaveText(legacy)
  // Long legacy values must stay inside the mobile grid instead of widening
  // the viewport and shifting click targets under the sticky save toolbar.
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await crops.click()
  await expect(page.getByRole('option', {name: legacy, exact: true})).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('option', {name: 'Blé', exact: true}).click()
  await page.keyboard.press('Escape')
  const missingCrops = page.getByRole('group', {name: seasonNeedsTitle, exact: true}).getByRole('button', {name: 'Cultures irriguées', exact: true})
  await missingCrops.click()
  await page.getByRole('option', {name: 'Blé', exact: true}).click()
  await page.keyboard.press('Escape')
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(missingCrops).toHaveAttribute('aria-invalid', 'true')
  await expect(missingCrops).toBeFocused()
  await expect(page.getByText('Sélectionnez les cultures, ou choisissez « Aucune ».', {exact: true})).toBeVisible()
  expect(await requests()).toHaveLength(0)
  await missingCrops.click()
  await page.getByRole('option', {name: 'Blé', exact: true}).click()
  await page.keyboard.press('Escape')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  expect((await requests())[0].body.data.meters[0].offSeason.crops).toEqual([legacy, 'Blé'])
  await page.reload()
  await crops.click()
  await expect(page.getByRole('option', {name: legacy, exact: true})).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('option', {name: 'Blé', exact: true})).toHaveAttribute('aria-selected', 'true')
  await page.keyboard.press('Escape')
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  await expect(page.getByText(`${legacy}, Blé`, {exact: true})).toBeVisible()
  await expect(page.getByRole('button', {name: 'Cultures irriguées', exact: true})).toHaveCount(0)
  const writes = await requests()
  expect(writes).toHaveLength(2)
  expect(writes[1].body.data.meters[0].offSeason.crops).toEqual([legacy, 'Blé'])
})

test('usages et sous-usages restent proposés, indentés et sélectionnables sans recherche', async ({page, context}, testInfo) => {
  const requests = await authenticate(context)
  await page.goto(responseUrl)
  const usage = page.getByRole('combobox', {name: 'Usage hors étiage', exact: true}).first()
  await usage.click()
  const choices = page.getByRole('listbox')
  await expect(choices).toBeInViewport()
  const inputBounds = await usage.boundingBox()
  const menuBounds = await choices.boundingBox()
  expect(Math.abs(menuBounds.width - inputBounds.width)).toBeLessThanOrEqual(2)
  const parent = choices.getByRole('option', {name: 'Irrigation', exact: true})
  const child = choices.getByRole('option', {name: 'Aspersion — Irrigation', exact: true})
  await expect(parent).toHaveAttribute('data-usage-level', 'parent')
  await expect(child).toHaveAttribute('data-usage-level', 'child')
  await expect(choices.getByRole('option').first()).toHaveText('Usage inconnu')
  expect((await parent.boundingBox()).height).toBeGreaterThanOrEqual(44)
  const parentLabel = await parent.locator('.campaign-usage-option-label').boundingBox()
  const childLabel = await child.locator('.campaign-usage-option-label').boundingBox()
  expect(childLabel.x).toBeGreaterThan(parentLabel.x + 15)
  await page.screenshot({path: testInfo.outputPath('usages-campagne.png')})
  await usage.press('ArrowDown')
  await usage.press('ArrowDown')
  await usage.press('Enter')
  await expect(usage).toHaveValue('Irrigation')
  await usage.click()
  await expect(choices).toBeVisible()
  await expect(parent).toHaveAttribute('aria-selected', 'true')
  await usage.press('End')
  await expect(usage).toHaveAttribute('aria-activedescendant', /option-6$/)
  await usage.press('Home')
  await expect(usage).toHaveAttribute('aria-activedescendant', /option-0$/)
  await usage.press('Tab')
  await expect(choices).toHaveCount(0)
  const secondUsage = page.getByRole('combobox', {name: 'Usage étiage', exact: true}).first()
  await secondUsage.fill('Asper')
  await expect(page.getByRole('option')).toHaveCount(1)
  await expect(child).toContainText('Irrigation')
  await secondUsage.press('Escape')
  await expect(page.getByRole('option')).toHaveCount(0)
  await secondUsage.press('ArrowDown')
  await expect(page.getByRole('option')).toHaveCount(7)
  await secondUsage.fill('Asp')
  await expect(page.getByRole('option')).toHaveCount(1)
  await secondUsage.press('Enter')
  await expect(secondUsage).toHaveValue('Aspersion')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByRole('region', {name: 'Enregistrement de la réponse', exact: true}).getByRole('status')).toHaveText('Brouillon enregistré.')
  expect((await requests())[0].body.data.meters[0]).toMatchObject({offSeason: {usageId: campaignIds.parentUsage}, season: {usageId: campaignIds.usage}})
  await page.reload()
  await expect(usage).toHaveValue('Irrigation')
  await expect(secondUsage).toHaveValue('Aspersion')
})

for (const role of ['preleveur', 'collector-fresh']) {
  test(`${role} : les usages autorisés sont les seuls choix des quatre périodes du bilan et des besoins`, async ({page, context}) => {
    const requests = await authenticate(context, `${role}-complete`)
    await page.goto(responseUrl)
    const periods = ['meters.0.offSeason', 'meters.0.season', 'needs.season', 'needs.offSeason']
    const choices = [
      'Usage inconnu', 'Pas d’usage', 'Irrigation', 'Aspersion — Irrigation', 'Goutte-à-goutte — Irrigation',
      'Réalimentation d’une ressource en eau', 'Remplissage plan d’eau — Réalimentation d’une ressource en eau'
    ]
    const selections = [
      {id: campaignIds.unknownUsage, label: 'Usage inconnu'},
      {id: campaignIds.noUsage, label: 'Pas d’usage'},
      {id: campaignIds.secondUsage, label: 'Goutte-à-goutte — Irrigation'},
      {id: campaignIds.fillingUsage, label: 'Remplissage plan d’eau — Réalimentation d’une ressource en eau'}
    ]
    for (const [index, path] of periods.entries()) {
      const usage = page.locator(`[name="${path}.usageId"]`)
      await usage.click()
      await expect(page.getByRole('option')).toHaveCount(choices.length)
      for (const label of choices) await expect(page.getByRole('option', {name: label, exact: true})).toBeVisible()
      await usage.fill('Industrie')
      await expect(page.getByRole('option')).toHaveCount(0)
      await expect(page.getByText('Aucun usage trouvé.', {exact: true})).toBeVisible()
      await usage.fill('')
      await page.getByRole('option', {name: selections[index].label, exact: true}).click()
    }
    await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
    await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
    const data = (await requests())[0].body.data
    expect([data.meters[0].offSeason, data.meters[0].season, data.needs.season, data.needs.offSeason].map(period => period.usageId)).toEqual(selections.map(usage => usage.id))
  })

  for (const source of ['draft', 'prefill']) {
    test(`${role} : les usages hors liste du ${source} restent affichés, enregistrables et envoyables`, async ({page, context}) => {
      const requests = await authenticate(context, `${role}-outsideusage${source === 'prefill' ? '-prefill' : ''}`)
      await page.goto(responseUrl)
      const periods = [
        {path: 'meters.0.offSeason', id: campaignIds.industryUsage, label: 'Industrie'},
        {path: 'meters.0.season', id: campaignIds.industrialChildUsage, label: 'Refroidissement industriel'},
        {path: 'needs.season', id: campaignIds.drinkingUsage, label: 'Alimentation en eau potable'},
        {path: 'needs.offSeason', id: campaignIds.industryUsage, label: 'Industrie'}
      ]
      if (source === 'prefill') await expect(page.getByText('Données préremplies à vérifier.', {exact: true})).toBeVisible()
      for (const {path, label} of periods) {
        const usage = page.locator(`[name="${path}.usageId"]`)
        await expect(usage).toHaveValue(label)
        await usage.click()
        await expect(page.getByRole('option')).toHaveCount(7)
        await expect(page.getByRole('option', {name: /Industrie|Refroidissement industriel|Alimentation en eau potable/})).toHaveCount(0)
        await usage.press('Escape')
        await expect(usage).toHaveValue(label)
      }
      await page.locator('[name="needs.season.volume"]').fill('125')
      await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
      await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
      await page.reload()
      for (const {path, label} of periods) await expect(page.locator(`[name="${path}.usageId"]`)).toHaveValue(label)
      await page.getByRole('button', {name: role === 'preleveur' ? 'Envoyer ma réponse' : 'Envoyer la réponse', exact: true}).click()
      await expect(page.getByText(role === 'preleveur' ? 'Votre réponse a bien été envoyée.' : 'La réponse a bien été envoyée.', {exact: true})).toBeVisible()
      const writes = await requests()
      expect(writes.map(write => [write.method, write.body.revision])).toEqual([['PUT', 0], ['POST', 1]])
      for (const write of writes) {
        const {data} = write.body
        expect([data.meters[0].offSeason, data.meters[0].season, data.needs.season, data.needs.offSeason].map(period => period.usageId)).toEqual(periods.map(period => period.id))
        expect(data.needs.season.volume).toBe('125')
      }
      for (const {path, label} of periods) {
        await expect(page.locator(`[name="${path}.usageId"]`)).toHaveValue(label)
        await expect(page.locator(`[name="${path}.usageId"]`)).toHaveAttribute('readonly', '')
      }
    })
  }
}

test('les propositions sont modifiables, enregistrables puis soumises sans données agricoles en réalimentation', async ({page, context}) => {
  const requests = await authenticate(context, 'prefill')
  await page.goto(responseUrl)
  await expect(page.getByText('Données préremplies à vérifier.', {exact: true})).toBeVisible()
  await expect(page.getByText('À compléter', {exact: true})).toBeVisible()
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveValue('10')
  await expect(page.locator('[name="meters.0.offSeason.indexEnd"]')).toHaveValue('')
  await expect(page.locator('[name="needs.offSeason.volume"]')).toHaveValue(/75\s000/)
  expect(await requests()).toHaveLength(0)

  await page.locator('[name="needs.offSeason.volume"]').fill('76000')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  await expect(page.getByText('Données préremplies à vérifier.', {exact: true})).toHaveCount(0)
  await page.reload()
  await expect(page.locator('[name="needs.offSeason.volume"]')).toHaveValue(/76\s000/)
  await page.locator('[name="meters.0.offSeason.indexEnd"]').fill('20')
  await page.locator('[name="meters.0.season.indexEnd"]').fill('30')
  for (const usage of await page.getByRole('combobox').all()) {
    await usage.click()
    await usage.fill('Remplissage')
    await page.getByRole('option', {name: 'Remplissage plan d’eau — Réalimentation d’une ressource en eau', exact: true}).click()
  }
  for (const surface of await page.locator('input[name$=".surface"]').all()) {
    await expect(surface).toHaveAttribute('aria-required', 'false')
    await surface.fill('')
  }
  for (const label of await page.locator('label[for$="-surface"], label[for$="-crops"]').all()) {
    await expect(label).not.toContainText('*')
  }
  await expect(page.getByRole('button', {name: 'Cultures irriguées (facultatif)', exact: true})).toHaveCount(4)
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  const writes = await requests()
  expect(writes).toHaveLength(2)
  expect(writes[1].path.endsWith('/submit')).toBe(true)
  expect(writes[1].body.data.needs.offSeason).toMatchObject({volume: '76000', usageId: campaignIds.fillingUsage, surface: '', crops: []})
  expect(writes[1].body.data.meters[0].offSeason).toMatchObject({indexStart: '10', indexEnd: '20', usageId: campaignIds.fillingUsage, surface: '', crops: []})
  expect(writes[1].body.data).not.toHaveProperty('prefill')
})

test('sans usage autorisé est une information précédente, pas une réponse ni une interdiction de demander', async ({page, context}) => {
  const requests = await authenticate(context, 'prefill-unauthorized')
  await page.goto(responseUrl)
  const notice = page.getByText('Autorisation précédente : aucun usage autorisé hors étiage.', {exact: true})
  await expect(notice).toHaveCount(0)
  const needs = page.getByRole('group', {name: offSeasonNeedsTitle, exact: true})
  await expect(needs.getByRole('combobox')).toHaveValue('')
  await expect(page.locator('[name="needs.offSeason.volume"]')).toHaveValue('')
  await expect(page.locator('[name="meters.0.offSeason.indexEnd"]')).toHaveValue('')
  await needs.getByRole('combobox').click()
  await needs.getByRole('combobox').fill('Remplissage')
  await page.getByRole('option', {name: /Remplissage plan d’eau/}).click()
  await page.locator('[name="needs.offSeason.volume"]').fill('5000')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  await expect(notice).toHaveCount(0)
  expect((await requests())[0].body.data.needs.offSeason).toMatchObject({usageId: campaignIds.fillingUsage, volume: '5000'})
})

test('changer d’usage actualise les erreurs agricoles sans effacer une surface ou des cultures saisies', async ({page, context}) => {
  const requests = await authenticate(context, 'complete')
  await page.goto(responseUrl)
  const needs = page.getByRole('group', {name: offSeasonNeedsTitle, exact: true})
  const usage = needs.getByRole('combobox')
  await usage.click()
  const parent = page.getByRole('option', {name: 'Réalimentation d’une ressource en eau', exact: true})
  const child = page.getByRole('option', {name: 'Remplissage plan d’eau — Réalimentation d’une ressource en eau', exact: true})
  await expect(parent).toHaveAttribute('data-usage-level', 'parent')
  await expect(child).toHaveAttribute('data-usage-level', 'child')
  await usage.fill('Remplissage')
  await usage.press('ArrowDown')
  await usage.press('Enter')
  await expect(usage).toHaveValue('Remplissage plan d’eau')
  await expect(page.locator('[name="needs.offSeason.surface"]')).toHaveValue('2')
  await expect(needs.getByRole('button', {name: 'Cultures irriguées (facultatif)', exact: true})).toHaveText('Maïs')
  await page.locator('[name="needs.offSeason.surface"]').fill('')
  await needs.getByRole('button', {name: 'Cultures irriguées (facultatif)', exact: true}).click()
  // Clear the historical free-text Maïs value without inventing an Aucune answer.
  await page.getByRole('option', {name: 'Maïs', exact: true}).click()
  await page.keyboard.press('Escape')
  await usage.fill('Aspersion')
  await page.getByRole('option', {name: /Aspersion/}).click()
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.locator('[name="needs.offSeason.surface"]')).toHaveAttribute('aria-invalid', 'true')
  await expect(needs.getByText('Sélectionnez les cultures, ou choisissez « Aucune ».', {exact: true})).toBeVisible()
  expect(await requests()).toHaveLength(0)
  await usage.fill('Réalimentation')
  await page.getByRole('option', {name: 'Réalimentation d’une ressource en eau', exact: true}).click()
  await expect(page.locator('[name="needs.offSeason.surface"]')).toHaveAttribute('aria-invalid', 'false')
  await expect(needs.getByText('Sélectionnez les cultures, ou choisissez « Aucune ».', {exact: true})).toHaveCount(0)
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  expect((await requests())[0].body.data.needs.offSeason).toMatchObject({usageId: campaignIds.replenishmentUsage, surface: '', crops: []})
})

test('les champs du demandeur attendent l’activation de l’interface avant d’accepter une interaction', async ({page, context}) => {
  const requests = await authenticate(context)
  const scripts = Promise.withResolvers()
  await page.route(`${frontUrl}/_next/static/**/*.js`, async route => {
    await scripts.promise
    await route.continue()
  })
  const usage = page.getByRole('combobox', {name: 'Usage hors étiage', exact: true}).first()
  try {
    await page.goto(responseUrl, {waitUntil: 'commit'})
    await expect(usage).toBeVisible()
    await expect(usage).toBeDisabled()
    await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toBeDisabled()
    await expect(page.getByRole('button', {name: 'Envoyer ma réponse', exact: true})).toBeDisabled()
    await expect(page.getByRole('option')).toHaveCount(0)
  } finally {
    scripts.resolve()
  }
  await expect(usage).toBeEnabled()
  await usage.click()
  await page.getByRole('option', {name: 'Irrigation', exact: true}).click()
  await expect(usage).toHaveValue('Irrigation')
  expect(await requests()).toHaveLength(0)
})

test('les index attendent la sortie du champ : frappe 2, 20, 200 sans signalement et correction au blur', async ({page, context}) => {
  const requests = await authenticate(context, 'complete')
  await page.goto(responseUrl)
  const start = page.locator('[name="meters.0.offSeason.indexStart"]')
  const middle = page.locator('[name="meters.0.offSeason.indexEnd"]')
  const end = page.locator('[name="meters.0.season.indexEnd"]')
  const changed = page.getByRole('checkbox', {name: 'Je souhaite signaler un changement de compteur', exact: true})
  const reason = page.getByRole('textbox', {name: 'Motif du changement de compteur', exact: true})
  await end.fill('300')
  await end.press('Tab')
  await middle.fill('200')
  await middle.press('Tab')
  await start.fill('100')
  await start.press('Tab')
  await expect(changed).not.toBeChecked()

  await middle.fill('')
  for (const [digit, value] of [['2', '2'], ['0', '20'], ['0', '200']]) {
    await middle.pressSequentially(digit)
    await expect(middle).toHaveValue(value)
    await expect(middle).toBeFocused()
    await expect(middle).toHaveAttribute('aria-invalid', 'false')
    await expect(changed).not.toBeChecked()
    await expect(reason).toHaveCount(0)
  }
  await middle.press('Tab')
  await expect(changed).not.toBeChecked()
  await expect(reason).toHaveCount(0)

  await middle.fill('20')
  await expect(changed).not.toBeChecked()
  await expect(reason).toHaveCount(0)
  await middle.press('Tab')
  await expect(middle).toHaveAttribute('aria-invalid', 'true')
  await expect(changed).toBeChecked()
  await expect(changed).toBeDisabled()
  await expect(reason).toBeVisible()
  await expect(reason).toHaveAttribute('aria-required', 'true')

  await middle.fill('200')
  await expect(changed).toBeChecked()
  await expect(reason).toBeVisible()
  await middle.press('Tab')
  await expect(middle).toHaveAttribute('aria-invalid', 'false')
  await expect(changed).not.toBeChecked()
  await expect(changed).toBeEnabled()
  await expect(reason).toHaveCount(0)

  // Enter submits directly from the field, so save-time validation must also run.
  await middle.fill('20')
  await expect(middle).toBeFocused()
  await expect(changed).not.toBeChecked()
  await middle.press('Enter')
  await expect(changed).toBeChecked()
  await expect(reason).toBeFocused()
  await expect(reason).toHaveAttribute('aria-invalid', 'true')
  expect(await requests()).toHaveLength(0)
})

test('les index d’un compteur sont croissants : signalement au blur, brouillon conservé et égalité autorisée', async ({page, context}) => {
  const requests = await authenticate(context, 'complete')
  await page.goto(responseUrl)
  const middle = page.locator('[name="meters.0.offSeason.indexEnd"]')
  const end = page.locator('[name="meters.0.season.indexEnd"]')
  await middle.fill('9')
  await middle.press('Tab')
  await expect(middle).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByText('L’index du 31/05/2026 doit être supérieur ou égal à celui du 01/11/2025.', {exact: true})).toBeVisible()
  await end.fill('8')
  await end.press('Tab')
  await expect(end).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByText('L’index du 31/10/2026 doit être supérieur ou égal à celui du 31/05/2026.', {exact: true})).toBeVisible()
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByRole('textbox', {name: 'Motif du changement de compteur', exact: true})).toBeFocused()
  expect(await requests()).toHaveLength(0)
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByRole('region', {name: 'Enregistrement de la réponse', exact: true}).getByRole('status')).toHaveText('Brouillon enregistré. Complétez le motif du changement de compteur ou corrigez les index avant l’envoi.')
  expect((await requests())[0].body.data.meters[0]).toMatchObject({offSeason: {indexStart: '10', indexEnd: '9'}, season: {indexEnd: '8'}})
  await page.reload()
  await expect(middle).toHaveValue('9')
  await expect(end).toHaveValue('8')
  await middle.fill('10')
  await end.fill('10')
  await end.press('Tab')
  await expect(middle).toHaveAttribute('aria-invalid', 'false')
  await expect(end).toHaveAttribute('aria-invalid', 'false')
  await page.getByRole('checkbox', {name: 'Je souhaite signaler un changement de compteur', exact: true}).focus()
  await page.getByRole('checkbox', {name: 'Je souhaite signaler un changement de compteur', exact: true}).press('Space')
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  const writes = await requests()
  expect(writes).toHaveLength(2)
  expect(writes[1].path.endsWith('/submit')).toBe(true)
  expect(writes[1].body.data.meters[0]).toMatchObject({offSeason: {indexStart: '10', indexEnd: '10'}, season: {indexEnd: '10'}})
})

test('la carte est affichée dès l’ouverture et n’est pas recréée pendant la saisie', async ({page, context}, testInfo) => {
  const requests = await authenticate(context, 'map')
  await page.goto(responseUrl)
  const map = page.getByRole('region', {name: 'Localisation du point de prélèvement', exact: true})
  await expect(map).toBeVisible()
  await expect(page.getByRole('button', {name: /Afficher la carte|Voir la carte/})).toHaveCount(0)
  const mapSurface = map.locator('canvas, [data-map-unavailable]')
  await expect(mapSurface).toBeVisible()
  const originalSurface = await mapSurface.elementHandle()
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('123')
  await page.locator('[name="meters.0.offSeason.indexEnd"]').fill('124')
  expect(await originalSurface.evaluate(element => element.isConnected)).toBe(true)
  expect(await requests()).toHaveLength(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await map.screenshot({path: testInfo.outputPath('carte-campagne-visible.png')})
})

test('les compteurs connus restent distincts sans proposer d’ajout de compteur', async ({page, context}) => {
  const requests = await authenticate(context)
  await page.goto(responseUrl)
  await expect(page.getByRole('button', {name: 'Ajouter un compteur', exact: true})).toHaveCount(0)
  await expect(page.getByRole('button', {name: 'Retirer ce compteur', exact: true})).toHaveCount(0)
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('25')
  await page.locator('[name="meters.1.offSeason.indexStart"]').fill('50')
  const secondUsage = page.getByRole('combobox', {name: 'Usage hors étiage', exact: true}).nth(1)
  await secondUsage.click()
  await secondUsage.fill('Goutte')
  await page.getByRole('option', {name: /Goutte-à-goutte/}).click()
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  expect((await requests())[0].body.data.meters).toMatchObject([
    {compteurId: campaignIds.meter, serialNumber: 'SYNTH-M1', offSeason: {indexStart: '25'}},
    {compteurId: campaignIds.secondMeter, serialNumber: 'SYNTH-M2', offSeason: {indexStart: '50', usageId: campaignIds.secondUsage}}
  ])
  await page.reload()
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveValue('25')
  await expect(page.locator('[name="meters.1.offSeason.indexStart"]')).toHaveValue('50')
  await expect(secondUsage).toHaveValue('Goutte-à-goutte')
})

test('les champs numériques expliquent la correction attendue sans transformer les valeurs invalides', async ({page, context}) => {
  const requests = await authenticate(context, 'complete')
  await page.goto(responseUrl)
  const index = page.locator('[name="meters.0.offSeason.indexStart"]')
  const volume = page.locator('[name="needs.season.volume"]')
  const flow = page.locator('[name="needs.season.flow"]')
  const surface = page.locator('[name="needs.season.surface"]')
  await index.fill('-1')
  await volume.fill('')
  await flow.fill('1e3')
  await surface.fill('1,23456')
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(index).toHaveValue('-1')
  await expect(flow).toHaveValue('1e3')
  await expect(page.getByText('L’index du compteur doit être supérieur ou égal à zéro.', {exact: true})).toBeVisible()
  await expect(page.getByText('Renseignez le volume demandé en m³.', {exact: true})).toBeVisible()
  await expect(page.getByText('Vérifiez le débit demandé en m³/h.', {exact: true})).toBeVisible()
  await expect(page.getByText('Vérifiez la surface irriguée en hectares.', {exact: true})).toBeVisible()
  await expect(page.getByText(/chiffres avant la virgule/)).toHaveCount(0)
  expect(await requests()).toHaveLength(0)
  await index.fill('10')
  await volume.fill('0')
  await flow.fill('0')
  await surface.fill('0')
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  expect((await requests())[0].body.data.needs.season).toMatchObject({volume: '0', flow: '0', surface: '0'})
})

test('les erreurs métier de l’API et les champs invalides restent lisibles sans effacer la saisie', async ({page, context}) => {
  await authenticate(context, 'closed')
  await page.goto(responseUrl)
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('12')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText(/Cette campagne n’est pas ouverte à la saisie/)).toBeVisible()
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveValue('12')
  await authenticate(context, 'invalid')
  page.once('dialog', dialog => dialog.accept())
  await page.reload()
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('15')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Le relevé du compteur doit être vérifié.', {exact: true})).toBeVisible()
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveAttribute('aria-invalid', 'true')
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveValue('15')
})

test('collecteur : navigation, export des résultats envoyés et correction de la réponse', async ({page, context, isMobile}, testInfo) => {
  const requests = await authenticate(context, 'collector')
  await page.goto(`${frontUrl}/campagnes/${campaignIds.campaign}`)
  if (isMobile) await page.getByRole('button', {name: 'Menu', exact: true}).click()
  await expect(page.getByRole('link', {name: 'Campagnes', exact: true})).toBeVisible()
  if (isMobile) await page.getByRole('button', {name: 'Fermer', exact: true}).click()
  await expect(page.getByRole('heading', {name: 'Points de la campagne', exact: true})).toBeVisible()
  await expect(page.getByText('Commune de test · Parcelle du moulin', {exact: true})).toBeVisible()
  await expect(page.getByText('Code compteur Agence de l’eau : 001', {exact: true})).toBeVisible()
  await expect(page.getByRole('searchbox', {name: 'Rechercher un point ou un préleveur', exact: true})).toHaveAttribute('placeholder', 'Nom du point, commune, code compteur, préleveur')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({path: testInfo.outputPath('points-campagne-collecteur.png'), fullPage: true})
  await page.getByRole('button', {name: 'Résultats envoyés', exact: true}).click()
  await expect(page.getByText('120 m³', {exact: true})).toBeVisible()
  await expect(page.getByRole('heading', {name: 'Volumes prélevés calculés', exact: true})).toBeVisible()
  await expect(page.locator('dd').filter({hasText: /^10 m³$/})).toHaveCount(2)
  await expect(page.locator('dd').filter({hasText: /^20 m³$/})).toHaveCount(1)
  await expect(page.getByText(/volumes en attente|Non calculé/i)).toHaveCount(0)
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', {name: 'Exporter tous les résultats (CSV)', exact: true}).click()
  expect((await downloaded).suggestedFilename()).toBe('resultats-campagne.csv')
  expect((await requests())[0].path.endsWith('/export')).toBe(true)
  await expect(page.getByRole('link', {name: 'Modifier la réponse', exact: true})).toHaveAttribute('href', `/campagnes/${campaignIds.campaign}/reponses/${campaignIds.response}?modifier=1`)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({path: testInfo.outputPath('resultats-modification-collecteur.png'), fullPage: true})
  await page.getByRole('link', {name: 'Consulter', exact: true}).click()
  await expect(page.getByText('Vous répondez pour Ferme synthétique. Le brouillon enregistré est partagé avec ce préleveur.', {exact: true})).toBeVisible()
  await expect(page.locator('[name="needs.season.volume"]')).toHaveValue('120')
  await expect(page.locator('[name="needs.season.volume"]')).toHaveAttribute('readonly', '')
  await expect(page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true})).toHaveCount(0)
  await expect(page.getByRole('button', {name: 'Modifier ma réponse', exact: true})).toHaveCount(0)
  await page.getByRole('link', {name: 'Retour à la campagne', exact: true}).click()
  await page.getByRole('button', {name: 'Résultats envoyés', exact: true}).click()
  await page.getByRole('link', {name: 'Modifier la réponse', exact: true}).click()
  await expect(page.locator('[name="needs.season.volume"]')).not.toHaveAttribute('readonly', '')
  await page.locator('[name="needs.season.volume"]').fill('150')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  await page.getByRole('link', {name: 'Retour à la campagne', exact: true}).click()
  await page.getByRole('button', {name: 'Résultats envoyés', exact: true}).click()
  await expect(page.getByText('120 m³ demandés · 4 m³/h', {exact: true})).toBeVisible()
  await page.getByRole('link', {name: 'Reprendre la modification', exact: true}).click()
  await expect(page.locator('[name="needs.season.volume"]')).toHaveValue('150')
  await page.getByRole('button', {name: 'Envoyer les modifications', exact: true}).click()
  await expect(page.getByText('La réponse a bien été envoyée.', {exact: true})).toBeVisible()
  const writes = await requests()
  expect(writes.slice(1).map(write => [write.method, write.body.revision])).toEqual([['PUT', 0], ['POST', 1]])
  expect(writes[2].body.data.needs.season.volume).toBe('150')
})

test('collecteur : compléter une réponse vide puis reprendre le brouillon', async ({page, context}) => {
  const requests = await authenticate(context, 'collector-fresh')
  await page.goto(`${frontUrl}/campagnes/${campaignIds.campaign}`)
  await page.getByRole('link', {name: 'Compléter', exact: true}).click()
  await expect(page.getByText(/Vous répondez pour Ferme synthétique/)).toBeVisible()
  await page.getByRole('button', {name: 'Envoyer la réponse', exact: true}).click()
  await expect(page.getByText('Vérifiez les champs signalés avant d’envoyer la réponse.', {exact: true})).toBeVisible()
  expect(await requests()).toHaveLength(0)
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('12')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  await page.getByRole('link', {name: 'Retour à la campagne', exact: true}).click()
  await page.getByRole('link', {name: 'Reprendre', exact: true}).click()
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveValue('12')
  expect((await requests())[0].body.revision).toBe(0)
})

test('collecteur et préleveur partagent le brouillon, conservent la saisie en conflit et peuvent reprendre après envoi', async ({page, context, browser}) => {
  const sessionId = randomUUID()
  const requests = await authenticate(context, 'complete-shared', sessionId)
  await page.goto(responseUrl)
  const collectorContext = await browser.newContext({ignoreHTTPSErrors: true, locale: 'fr-FR', timezoneId: 'Europe/Paris', reducedMotion: 'reduce'})
  try {
    await authenticate(collectorContext, 'collector-shared', sessionId)
    const collectorPage = await collectorContext.newPage()
    await collectorPage.route('**/*', route => [frontUrl, 'http://127.0.0.1:3417'].includes(new URL(route.request().url()).origin) ? route.continue() : route.abort())
    await collectorPage.clock.setFixedTime(new Date('2026-11-01T12:00:00Z'))
    await collectorPage.goto(`${frontUrl}/campagnes/${campaignIds.campaign}`)
    await collectorPage.getByRole('link', {name: 'Reprendre', exact: true}).click()
    await expect(collectorPage.locator('[name="needs.season.volume"]')).toHaveValue('120')
    await page.locator('[name="needs.season.volume"]').fill('175')
    await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
    await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
    await collectorPage.locator('[name="needs.season.volume"]').fill('200')
    await collectorPage.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
    await expect(collectorPage.getByText('Révision périmée. Vos saisies sont conservées ici.', {exact: true})).toBeVisible()
    await expect(collectorPage.locator('[name="needs.season.volume"]')).toHaveValue('200')
    collectorPage.once('dialog', dialog => dialog.accept())
    await collectorPage.reload()
    await expect(collectorPage.locator('[name="needs.season.volume"]')).toHaveValue('175')
    await collectorPage.locator('[name="needs.season.volume"]').fill('200')
    await collectorPage.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
    await expect(collectorPage.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
    await page.reload()
    await expect(page.locator('[name="needs.season.volume"]')).toHaveValue('200')
    await collectorPage.getByRole('button', {name: 'Envoyer la réponse', exact: true}).click()
    await expect(collectorPage.getByText('La réponse a bien été envoyée.', {exact: true})).toBeVisible()
    await page.reload()
    await expect(page.locator('[name="needs.season.volume"]')).toHaveValue('200')
    await expect(page.locator('[name="needs.season.volume"]')).toHaveAttribute('readonly', '')
    await page.getByRole('button', {name: 'Modifier ma réponse', exact: true}).click()
    await page.locator('[name="needs.season.volume"]').fill('250')
    await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
    await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
    await collectorPage.reload()
    await expect(collectorPage.locator('[name="needs.season.volume"]')).toHaveValue('250')
    await expect(collectorPage.locator('[name="needs.season.volume"]')).not.toHaveAttribute('readonly', '')
    const writes = await requests()
    expect(writes.map(write => [write.method, write.body.revision])).toEqual([['PUT', 0], ['PUT', 0], ['PUT', 1], ['POST', 2], ['PUT', 3]])
    expect(writes[3].path.endsWith('/submit')).toBe(true)
  } finally {
    await collectorContext.close()
  }
})

for (const role of ['collector-ended', 'collector-ended-complete-fresh']) {
  test(`collecteur (${role}) : une campagne clôturée reste consultable sans écriture`, async ({page, context}) => {
    const requests = await authenticate(context, role)
    await page.goto(`${frontUrl}/campagnes/${campaignIds.campaign}`)
    await expect(page.getByRole('link', {name: /Modifier la réponse|Reprendre la modification/})).toHaveCount(0)
    await page.getByRole('link', {name: 'Consulter', exact: true}).click()
    await expect(page.getByText(/Vous consultez la réponse de Ferme synthétique/)).toBeVisible()
    await page.goto(`${responseUrl}?modifier=1`)
    await expect(page.getByText(/Vous consultez la réponse de Ferme synthétique/)).toBeVisible()
    await expect(page.getByText('Cette collecte est clôturée. La réponse reste consultable.', {exact: true})).toBeVisible()
    await expect(page.locator('[name="needs.season.volume"]')).toHaveAttribute('readonly', '')
    await expect(page.getByRole('button', {name: /Modifier la réponse|Enregistrer le brouillon|Envoyer la réponse|Envoyer les modifications/})).toHaveCount(0)
    await page.locator('form').dispatchEvent('submit')
    expect(await requests()).toHaveLength(0)
  })
}

test('admin : sélection groupée locale puis création du brouillon', async ({page, context}) => {
  const requests = await authenticate(context, 'admin')
  await page.goto(`${frontUrl}/administration/campagnes/nouvelle`)
  await page.getByLabel('Nom de la campagne', {exact: true}).fill('Collecte de test')
  await page.getByLabel('Collecteur destinataire', {exact: true}).selectOption(campaignIds.collector)
  await page.getByRole('button', {name: 'Sélectionner les 1 résultats', exact: true}).click()
  await expect(page.getByText('1 exploitation sélectionnée', {exact: true})).toBeVisible()
  await page.getByRole('button', {name: 'Tout désélectionner', exact: true}).click()
  expect(await requests()).toEqual([])
  await page.getByRole('checkbox', {name: /Point synthétique/}).check()
  await page.getByRole('button', {name: 'Créer le brouillon', exact: true}).click()
  await expect(page).toHaveURL(`${frontUrl}/administration/campagnes/${campaignIds.campaign}`)
  const writes = await requests()
  expect(writes).toHaveLength(1)
  expect(writes[0].body).toMatchObject({opensOn: null, closesOn: null, exploitationIds: [campaignIds.exploitation], collecteurUserId: campaignIds.collector})
})

test('avant le 31 octobre, une réponse incomplète reste signalée et les index saisis sont conservés en brouillon', async ({page, context}) => {
  const requests = await authenticate(context, 'before')
  await page.clock.setFixedTime(new Date('2026-09-24T12:00:00Z'))
  await page.goto(responseUrl)
  const submit = page.getByRole('button', {name: 'Envoyer ma réponse', exact: true})
  await expect(submit).toBeEnabled()
  await expect(page.getByText(/Le bilan pourra être envoyé à partir du 31 octobre 2026/)).toHaveCount(0)
  await submit.click()
  const start = page.locator('[name="meters.0.offSeason.indexStart"]')
  await expect(start).toBeFocused()
  await expect(start).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByRole('button', {name: /Voir les champs à corriger/})).toBeVisible()
  expect(await requests()).toHaveLength(0)
  await page.locator('[name="meters.0.offSeason.indexStart"]').fill('5')
  await page.locator('[name="meters.0.season.indexEnd"]').fill('30')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  const writes = await requests()
  expect(writes).toHaveLength(1)
  expect(writes[0]).toMatchObject({method: 'PUT', path: `/api/campaigns/${campaignIds.campaign}/responses/${campaignIds.response}`})
  expect(writes[0].body.data.meters[0]).toMatchObject({offSeason: {indexStart: '5'}, season: {indexEnd: '30'}})
  await page.reload()
  await expect(start).toHaveValue('5')
  await expect(page.locator('[name="meters.0.season.indexEnd"]')).toHaveValue('30')
})

test('avant le 31 octobre, une réponse complète peut être reprise, envoyée et corrigée', async ({page, context}) => {
  const requests = await authenticate(context, 'before-complete')
  await page.clock.setFixedTime(new Date('2026-09-24T12:00:00Z'))
  await page.goto(responseUrl)
  const submit = page.getByRole('button', {name: 'Envoyer ma réponse', exact: true})
  await expect(submit).toBeEnabled()
  await expect(page.getByText(/Le bilan pourra être envoyé à partir du 31 octobre 2026/)).toHaveCount(0)
  const end = page.getByRole('textbox', {name: 'Index au 31/10/2026', exact: true})
  await end.fill('35')
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await expect(page.getByText('Brouillon enregistré.', {exact: true})).toBeVisible()
  await page.reload()
  await expect(end).toHaveValue('35')
  await submit.click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  await expect(page.getByText('Premier envoi : 24/09/2026 · Dernier envoi : 24/09/2026', {exact: true})).toBeVisible()
  await expect(page.getByRole('heading', {name: 'Volumes prélevés calculés', exact: true})).toBeVisible()
  await expect(page.locator('dd').filter({hasText: /^25 m³$/})).toHaveCount(1)
  await expect(page.locator('form [aria-invalid="true"]')).toHaveCount(0)
  await page.reload()
  await expect(end).toHaveValue('35')
  await expect(end).toHaveAttribute('readonly', '')
  await page.getByRole('button', {name: 'Modifier ma réponse', exact: true}).click()
  await end.fill('40')
  await page.getByRole('button', {name: 'Envoyer les modifications', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  const writes = await requests()
  expect(writes).toHaveLength(3)
  expect(writes[0]).toMatchObject({method: 'PUT', path: `/api/campaigns/${campaignIds.campaign}/responses/${campaignIds.response}`, body: {revision: 0}})
  expect(writes[1]).toMatchObject({method: 'POST', path: `/api/campaigns/${campaignIds.campaign}/responses/${campaignIds.response}/submit`, body: {revision: 1}})
  expect(writes[2]).toMatchObject({method: 'POST', path: `/api/campaigns/${campaignIds.campaign}/responses/${campaignIds.response}/submit`, body: {revision: 2}})
  expect(writes.map(write => write.body.data.meters[0].season.indexEnd)).toEqual(['35', '35', '40'])
  await page.reload()
  await expect(end).toHaveValue('40')
  await expect(end).toHaveAttribute('readonly', '')
  await expect(page.getByText(/Le bilan pourra être envoyé à partir du 31 octobre 2026/)).toHaveCount(0)
})

test('admin : une ancienne réponse à vérifier affiche ses volumes sans parcours de validation', async ({page, context}, testInfo) => {
  const requests = await authenticate(context, 'admin-review')
  await page.goto(`${frontUrl}/administration/campagnes/${campaignIds.campaign}/reponses/${campaignIds.response}`)
  await expect(page.getByRole('heading', {name: 'Volumes prélevés calculés', exact: true})).toBeVisible()
  await expect(page.locator('dd').filter({hasText: /^10 m³$/})).toHaveCount(2)
  await expect(page.locator('dd').filter({hasText: /^20 m³$/})).toHaveCount(1)
  await expect(page.getByRole('button', {name: /Vérifier le compteur|Valider et publier/})).toHaveCount(0)
  await expect(page.getByRole('checkbox', {name: /Je confirme que ces rattachements/})).toHaveCount(0)
  await expect(page.getByText(/en attente de|doit être vérifié|publiés/i)).toHaveCount(0)
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveAttribute('readonly', '')
  await page.screenshot({path: testInfo.outputPath('reponse-volumes-calcules-sans-validation.png'), fullPage: true})
  await page.goto(`${frontUrl}/administration/campagnes/${campaignIds.campaign}`)
  await expect(page.getByText(/en attente de|doit être vérifié/i)).toHaveCount(0)
  await page.getByRole('button', {name: 'Résultats envoyés', exact: true}).click()
  await expect(page.locator('dd').filter({hasText: /^20 m³$/})).toHaveCount(1)
  await expect(page.getByText(/en attente de|doit être vérifié/i)).toHaveCount(0)
  expect(await requests()).toHaveLength(0)
})

test('la déclaration générée distingue ses compteurs et renvoie vers la réponse de campagne', async ({page, context}) => {
  await authenticate(context)
  await page.goto(`${frontUrl}/mes-declarations/${campaignIds.declaration}`)
  await expect(page.getByText('Compteur : SYNTH-M1', {exact: true})).toBeVisible()
  await expect(page.getByText('Compteur : SYNTH-M2', {exact: true})).toBeVisible()
  await expect(page.getByRole('link', {name: 'Consulter la réponse et les volumes calculés', exact: true})).toHaveAttribute('href', `/campagnes/${campaignIds.campaign}/reponses/${campaignIds.response}`)
  await page.getByText('Voir les derniers index connus', {exact: true}).first().click()
  await expect(page.getByRole('columnheader', {name: 'Compteur', exact: true}).first()).toBeVisible()
  await expect(page.getByRole('cell', {name: 'SYNTH-M1', exact: true})).toBeVisible()
})

test('le reçu conserve la notice pour l’instructeur et oriente l’admin vers la gestion de campagne', async ({page, context}) => {
  await authenticate(context, 'instructor')
  await page.goto(`${frontUrl}/declarations/synthetic-source`)
  await expect(page.getByText('Ces index proviennent d’une campagne.', {exact: true})).toBeVisible()
  await expect(page.getByRole('link', {name: 'Consulter la réponse et les volumes calculés', exact: true})).toHaveCount(0)
  await authenticate(context, 'admin')
  await page.reload()
  await expect(page.getByRole('link', {name: 'Consulter la réponse et les volumes calculés', exact: true})).toHaveAttribute('href', `/administration/campagnes/${campaignIds.campaign}/reponses/${campaignIds.response}`)
})


test('un changement automatique conserve le motif et la période calculable, sans validation', async ({page, context}) => {
  const requests = await authenticate(context, 'complete')
  await page.goto(responseUrl)
  const changed = page.getByRole('checkbox', {name: 'Je souhaite signaler un changement de compteur', exact: true})
  const reason = page.getByRole('textbox', {name: 'Motif du changement de compteur', exact: true})
  const middle = page.locator('[name="meters.0.offSeason.indexEnd"]')
  await middle.fill('5')
  await expect(changed).not.toBeChecked()
  await middle.press('Tab')
  await expect(changed).toBeChecked()
  await expect(changed).toBeDisabled()
  await page.getByRole('button', {name: 'Enregistrer le brouillon', exact: true}).click()
  await page.reload()
  await expect(changed).toBeChecked()
  await expect(reason).toHaveValue('')
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(reason).toBeFocused()
  expect(await requests()).toHaveLength(1)
  await reason.fill('Remplacement : nouveau compteur SYNTH-NEW')
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  await expect(changed).toBeChecked()
  await expect(page.locator('dd').filter({hasText: /^—$/})).toHaveCount(1)
  await expect(page.locator('dd').filter({hasText: /^25 m³$/})).toHaveCount(2)
  await expect(page.getByText(/volumes en attente de vérification/i)).toHaveCount(0)
  expect((await requests())[1].body.data.meters[0]).toMatchObject({meterChanged: true, meterChangeReason: 'Remplacement : nouveau compteur SYNTH-NEW'})
  await page.reload()
  await expect(reason).toHaveValue('Remplacement : nouveau compteur SYNTH-NEW')
  await expect(reason).toHaveAttribute('readonly', '')
})

test('une incohérence historique de l’API ouvre le motif sans perdre la réponse', async ({page, context}) => {
  const requests = await authenticate(context, 'complete-historical')
  await page.goto(responseUrl)
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  const changed = page.getByRole('checkbox', {name: 'Je souhaite signaler un changement de compteur', exact: true})
  await expect(changed).toBeChecked()
  await expect(changed).toBeDisabled()
  await expect(page.locator('[name="meters.0.offSeason.indexStart"]')).toHaveValue('10')
  const start = page.locator('[name="meters.0.offSeason.indexStart"]')
  await start.fill('11')
  await expect(changed).toBeChecked()
  await start.press('Tab')
  await expect(changed).not.toBeChecked()
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(changed).toBeChecked()
  await page.getByRole('textbox', {name: 'Motif du changement de compteur', exact: true}).fill('Nouveau compteur HIST-2')
  await page.getByRole('button', {name: 'Envoyer ma réponse', exact: true}).click()
  await expect(page.getByText('Votre réponse a bien été envoyée.', {exact: true})).toBeVisible()
  expect(await requests()).toHaveLength(3)
})

test('admin : le signalement reste visible dans les résultats et ne propose aucune validation', async ({page, context}) => {
  await authenticate(context, 'admin-changed')
  await page.goto(`${frontUrl}/administration/campagnes/${campaignIds.campaign}/reponses/${campaignIds.response}`)
  await expect(page.getByRole('textbox', {name: 'Motif du changement de compteur', exact: true})).toHaveValue('Remplacement, nouveau compteur SYNTH-NEW')
  await expect(page.getByRole('button', {name: /Vérifier le compteur/})).toHaveCount(0)
  await expect(page.locator('dd').filter({hasText: /^10 m³$/})).toHaveCount(2)
  await expect(page.locator('dd').filter({hasText: /^20 m³$/})).toHaveCount(1)
  await expect(page.getByText(/en attente de|Non calculé/i)).toHaveCount(0)
  const scripts = Promise.withResolvers()
  await page.route(`${frontUrl}/_next/static/**/*.js`, async route => {
    await scripts.promise
    await route.continue()
  })
  const results = page.getByRole('button', {name: 'Résultats envoyés', exact: true})
  try {
    await page.goto(`${frontUrl}/administration/campagnes/${campaignIds.campaign}`, {waitUntil: 'commit'})
    await expect(results).toBeVisible()
    await expect(results).toBeDisabled()
    await expect(page.getByRole('button', {name: 'Suivi des réponses', exact: true})).toBeDisabled()
  } finally {
    scripts.resolve()
  }
  await expect(results).toBeEnabled()
  await results.click()
  await expect(results).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('region', {name: 'Changements de compteur signalés'})).toContainText('Remplacement, nouveau compteur SYNTH-NEW')
  await expect(page.locator('dd').filter({hasText: /^20 m³$/})).toHaveCount(1)
  await expect(page.getByText(/hors étiage 10 m³ · étiage 10 m³/)).toBeVisible()
})

for (const ordinary of [false, true]) {
  test(`Mes déclarations et Mon activité proposent la campagne avec outil ordinaire disponible : ${ordinary}`, async ({page, context}) => {
    await authenticate(context, ordinary ? 'ordinary' : 'preleveur')
    for (const path of ['/mes-declarations', '/tableau-de-bord']) {
      await page.goto(frontUrl + path)
      await expect(page.getByRole('region', {name: 'Déclarer mes prélèvements et mes besoins', exact: true})).toBeVisible()
      await expect(page.getByRole('link', {name: 'Nouvelle déclaration', exact: true})).toHaveCount(ordinary ? 1 : 0)
    }
    if (!ordinary) {
      await page.goto(`${frontUrl}/mes-declarations/new`)
      await expect(page.getByRole('region', {name: 'Déclarer mes prélèvements et mes besoins', exact: true})).toBeVisible()
      await expect(page.getByText('Aucun mode de déclaration disponible', {exact: true})).toBeVisible()
      await expect(page.getByRole('textbox', {name: /^Index/})).toHaveCount(0)
    }
  })
}

test('l’avertissement de réalimentation reste sur la liste des compteurs, sans rappel dans le formulaire', async ({page, context}) => {
  await authenticate(context, 'multiple')
  await page.goto(`${frontUrl}/campagnes/${campaignIds.campaign}`)
  await expect(page.getByRole('heading', {name: 'Mes compteurs concernés', exact: true})).toBeVisible()
  await expect(page.getByText('Les points de réalimentation n’ont pas à être déclarés ici', {exact: true})).toBeVisible()
  await page.goto(responseUrl)
  await expect(page.getByRole('region', {name: 'Enregistrement de la réponse', exact: true})).toBeVisible()
  await expect(page.getByText('Les points de réalimentation n’ont pas à être déclarés ici', {exact: true})).toHaveCount(0)
})
