import {test, expect} from '@playwright/test'

const storiesUrl = 'http://127.0.0.1:3432'
const selectorLabel = 'Territoires de démonstration'
const searchLabel = 'Rechercher dans territoires de démonstration'

test.use({reducedMotion: 'reduce'})

test.beforeEach(async ({page}) => {
  await page.route('**/*', route => {
    const url = new URL(route.request().url())
    return url.origin === storiesUrl ? route.continue() : route.abort()
  })
})

const showStory = (page, story = 'selection-avec-validation') =>
  page.goto(`${storiesUrl}/iframe.html?id=components-groupedmultiselect--${story}&viewMode=story`)

const selector = page => page.getByRole('button', {name: selectorLabel, exact: true})
const search = page => page.getByRole('textbox', {name: searchLabel, exact: true})
const option = (page, name) => page.getByRole('option', {name, exact: true})
const appliedSelection = async page => JSON.parse(await page.getByLabel('Sélection appliquée', {exact: true}).textContent())

async function expectApplied(page, values, changes) {
  await expect.poll(() => appliedSelection(page)).toEqual(values)
  await expect(page.getByLabel('Nombre de changements appliqués', {exact: true})).toHaveText(String(changes))
  await expect(page.getByLabel('Soumissions du formulaire', {exact: true})).toHaveText('0')
}

async function openSelector(page) {
  await selector(page).click()
  await expect(search(page)).toBeFocused()
  await expect(page.getByRole('listbox', {name: selectorLabel, exact: true})).toBeVisible()
}

test('le mode historique applique chaque choix immédiatement, sans nouveaux boutons', async ({page}) => {
  await showStory(page, 'selection-immediate')
  await openSelector(page)
  await expect(page.getByRole('button', {name: 'Appliquer', exact: true})).toHaveCount(0)
  await expect(page.getByRole('button', {name: 'Tout sélectionner', exact: true})).toHaveCount(0)
  await option(page, 'Nord — Bêta').click()
  await expectApplied(page, ['north-a', 'north-b'], 1)
  await option(page, 'Nord — Alpha').click()
  await expectApplied(page, ['north-b'], 2)
  await page.keyboard.press('Escape')
  await expect(selector(page)).toHaveAttribute('aria-expanded', 'false')
  await expect(selector(page)).toBeFocused()
  await expectApplied(page, ['north-b'], 2)
})

test('plusieurs choix restent en brouillon puis sont appliqués en une seule fois', async ({page}) => {
  await showStory(page)
  await openSelector(page)
  await expect(page.getByRole('button', {name: 'Appliquer', exact: true})).toBeDisabled()
  await option(page, 'Nord — Bêta').click()
  await option(page, 'Sud — Gamma').click()
  await expect(option(page, 'Nord — Bêta')).toHaveAttribute('aria-selected', 'true')
  await expectApplied(page, ['north-a'], 0)
  await expect(selector(page)).toHaveText('Nord — Alpha')
  await page.getByRole('button', {name: 'Appliquer', exact: true}).click()
  await expectApplied(page, ['north-a', 'north-b', 'south-a'], 1)
  await expect(selector(page)).toBeFocused()
  await expect(selector(page)).toHaveAttribute('aria-expanded', 'false')
  await openSelector(page)
  await expect(page.getByRole('button', {name: 'Appliquer', exact: true})).toBeDisabled()
  await page.getByRole('button', {name: 'Annuler', exact: true}).click()
  await expectApplied(page, ['north-a', 'north-b', 'south-a'], 1)
})

test('les actions sur les résultats préservent les choix masqués et les options protégées', async ({page}) => {
  await showStory(page, 'selection-avec-options-protegees')
  await openSelector(page)
  await search(page).fill('Nord')
  await expect(option(page, 'Sud — Gamma')).toHaveCount(0)
  await page.getByRole('button', {name: 'Sélectionner les résultats', exact: true}).click()
  await expect(option(page, 'Nord — Bêta')).toHaveAttribute('aria-selected', 'true')
  await expect(option(page, 'Nord — Accès conservé')).toHaveAttribute('aria-disabled', 'true')
  await expectApplied(page, ['north-a', 'south-a', 'north-locked'], 0)
  await page.getByRole('button', {name: 'Désélectionner les résultats', exact: true}).click()
  await expect(option(page, 'Nord — Alpha')).toHaveAttribute('aria-selected', 'false')
  await expect(option(page, 'Nord — Bêta')).toHaveAttribute('aria-selected', 'false')
  await expect(option(page, 'Nord — Accès conservé')).toHaveAttribute('aria-selected', 'true')
  await search(page).fill('Sud')
  await expect(option(page, 'Sud — Gamma')).toHaveAttribute('aria-selected', 'true')
  await expect(option(page, 'Sud — Indisponible')).toHaveAttribute('aria-selected', 'false')
  await page.getByRole('button', {name: 'Appliquer', exact: true}).click()
  await expectApplied(page, ['south-a', 'north-locked'], 1)
})

test('Échap et Annuler abandonnent le brouillon et rendent le focus au sélecteur', async ({page}) => {
  await showStory(page)
  await openSelector(page)
  await option(page, 'Nord — Bêta').click()
  await search(page).focus()
  await search(page).press('Escape')
  await expect(selector(page)).toBeFocused()
  await expectApplied(page, ['north-a'], 0)
  await openSelector(page)
  await expect(option(page, 'Nord — Bêta')).toHaveAttribute('aria-selected', 'false')
  await option(page, 'Nord — Bêta').click()
  await page.getByRole('button', {name: 'Annuler', exact: true}).click()
  await expect(selector(page)).toBeFocused()
  await expectApplied(page, ['north-a'], 0)
})

test('le clic extérieur et la sortie par Tab abandonnent sans voler le focus', async ({page}) => {
  await showStory(page)
  await openSelector(page)
  await option(page, 'Nord — Bêta').click()
  const outside = page.getByRole('button', {name: 'Après le sélecteur', exact: true})
  await outside.click()
  await expect(selector(page)).toHaveAttribute('aria-expanded', 'false')
  // Safari does not always focus native buttons on mouse click; the selector
  // must not steal focus regardless of that platform convention.
  await expect(selector(page)).not.toBeFocused()
  await expectApplied(page, ['north-a'], 0)
  await openSelector(page)
  await expect(option(page, 'Nord — Bêta')).toHaveAttribute('aria-selected', 'false')
  await option(page, 'Nord — Bêta').click()
  await page.getByRole('button', {name: 'Appliquer', exact: true}).focus()
  await page.keyboard.press('Tab')
  await expect(outside).toBeFocused()
  await expect(selector(page)).toHaveAttribute('aria-expanded', 'false')
  await expectApplied(page, ['north-a'], 0)
})

test('le clavier traverse recherche, actions, options et validation sans soumettre le formulaire', async ({page}) => {
  await showStory(page)
  await selector(page).focus()
  await selector(page).press('Enter')
  await expect(search(page)).toBeFocused()
  await search(page).press('Enter')
  await expect(search(page)).toBeFocused()
  await expectApplied(page, ['north-a'], 0)
  await search(page).press('Tab')
  const selectAll = page.getByRole('button', {name: 'Tout sélectionner', exact: true})
  await expect(selectAll).toBeFocused()
  await selectAll.press('Enter')
  await expect(option(page, 'Nord — Bêta')).toHaveAttribute('aria-selected', 'true')
  await expect(option(page, 'Sud — Indisponible')).toHaveAttribute('aria-selected', 'false')
  await expectApplied(page, ['north-a'], 0)
  await search(page).focus()
  await search(page).press('ArrowDown')
  await expect(option(page, 'Nord — Alpha')).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(option(page, 'Nord — Bêta')).toBeFocused()
  await page.keyboard.press(' ')
  await expect(option(page, 'Nord — Bêta')).toHaveAttribute('aria-selected', 'false')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', {name: 'Annuler', exact: true})).toBeFocused()
  await page.keyboard.press('Tab')
  const apply = page.getByRole('button', {name: 'Appliquer', exact: true})
  await expect(apply).toBeFocused()
  await apply.press('Enter')
  await expectApplied(page, ['north-a', 'south-a'], 1)
  await expect(selector(page)).toBeFocused()
})

test('un brouillon vide empêche Appliquer et affiche le message minimum personnalisé', async ({page}) => {
  await showStory(page)
  await openSelector(page)
  await page.getByRole('button', {name: 'Tout désélectionner', exact: true}).click()
  await expect(page.getByRole('status')).toHaveText('Sélectionnez au moins un territoire.')
  const apply = page.getByRole('button', {name: 'Appliquer', exact: true})
  await expect(apply).toBeDisabled()
  await expect(apply).toHaveAccessibleDescription('Sélectionnez au moins un territoire.')
  await expectApplied(page, ['north-a'], 0)
  await option(page, 'Sud — Gamma').click()
  await expect(apply).toBeEnabled()
  await apply.click()
  await expectApplied(page, ['south-a'], 1)
})

test('le message minimum possède un libellé par défaut', async ({page}) => {
  await showStory(page, 'selection-minimum-par-defaut')
  await openSelector(page)
  await page.getByRole('button', {name: 'Tout désélectionner', exact: true}).click()
  await expect(page.getByRole('status')).toHaveText('Sélectionnez au moins une option.')
  await expect(page.getByRole('button', {name: 'Appliquer', exact: true})).toBeDisabled()
  await expectApplied(page, ['north-a'], 0)
})

test('une recherche sans résultat ne modifie pas les choix et les actions restent hors listbox', async ({page}) => {
  await showStory(page)
  await openSelector(page)
  await search(page).fill('introuvable')
  await expect(page.getByText('Aucune option', {exact: true})).toBeVisible()
  await expect(page.getByRole('option')).toHaveCount(0)
  await expect(page.getByRole('button', {name: 'Sélectionner les résultats', exact: true})).toBeDisabled()
  await expect(page.getByRole('button', {name: 'Désélectionner les résultats', exact: true})).toBeDisabled()
  const listbox = page.getByRole('listbox', {name: selectorLabel, exact: true})
  await expect(listbox.getByRole('button')).toHaveCount(0)
  await expect(listbox.getByRole('textbox')).toHaveCount(0)
  await search(page).press('ArrowDown')
  await expect(search(page)).toBeFocused()
  await search(page).press('Escape')
  await expect(selector(page)).toBeFocused()
  await expectApplied(page, ['north-a'], 0)
  await openSelector(page)
  await expect(search(page)).toHaveValue('')
  await expect(option(page, 'Nord — Alpha')).toHaveAttribute('aria-selected', 'true')
})

test('150 zones : désélectionner puis rechercher et choisir ne déclenche qu’une seule application', async ({page}, testInfo) => {
  await showStory(page, 'selection-nombreuses-zones')
  await openSelector(page)
  await expect(page.getByRole('option')).toHaveCount(150)
  await page.screenshot({path: testInfo.outputPath('selection-150-zones.png'), fullPage: true, animations: 'disabled'})
  await page.getByRole('button', {name: 'Tout désélectionner', exact: true}).click()
  await expect(page.getByRole('status')).toHaveText('Sélectionnez au moins un territoire.')
  await expect(page.getByRole('button', {name: 'Appliquer', exact: true})).toBeDisabled()
  await expect(page.getByLabel('Nombre de changements appliqués', {exact: true})).toHaveText('0')
  expect(await appliedSelection(page)).toHaveLength(150)
  await search(page).fill('Zone 075')
  await expect(page.getByRole('option')).toHaveCount(1)
  await option(page, 'Zone 075').click()
  await expect(page.getByLabel('Nombre de changements appliqués', {exact: true})).toHaveText('0')
  expect(await appliedSelection(page)).toHaveLength(150)
  await page.getByRole('button', {name: 'Appliquer', exact: true}).click()
  await expectApplied(page, ['zone-075'], 1)
})
