export const ZONE_ICONS = {
  add: 'ri-add-line',
  addUser: 'ri-user-add-line',
  arrowRight: 'ri-arrow-right-line',
  at: 'ri-at-line',
  briefcase: 'ri-briefcase-line',
  building: 'ri-building-line',
  calendar: 'ri-calendar-line',
  close: 'ri-close-line',
  dashboard: 'ri-dashboard-line',
  edit: 'ri-edit-line',
  eye: 'ri-eye-line',
  file: 'ri-file-line',
  hashtag: 'ri-hashtag',
  link: 'ri-links-line',
  mapPin: 'ri-map-pin-line',
  mapPin2: 'ri-map-pin-2-line',
  phone: 'ri-phone-line',
  search: 'ri-search-line',
  settings: 'ri-settings-5-line',
  shieldCheck: 'ri-shield-check-line',
  team: 'ri-team-line',
  user: 'ri-user-line',
  userSettings: 'ri-user-settings-line',
  userUnfollow: 'ri-user-unfollow-line',
  water: 'ri-drop-line'
}
